/*
	File: fn_clothing_reb.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Master configuration file for Reb shop.
*/
private["_filter"];
_filter = [_this,0,0,[0]] call BIS_fnc_param;
//Classname, Custom Display name (use nil for Cfg->DisplayName, price

//Shop Title Name
ctrlSetText[3103,"Muhli's Outlaw Laden"];

switch (_filter) do
{
	//Uniforms
	case 0:
	{
		[
			["I_FEM_AAF_long","Frauenkleidung",75],
			["B_FEM_AAF_Rolled","Frauenkleidung",75],
			["I_FEM_AAF","Frauenkleidung",75],
			["O_FEM_CSAT_Long","Frauenkleidung",75],
			["O_FEM_CSAT_Rolled","Frauenkleidung",75],
			["O_FEM_CSAT","Frauenkleidung",75],
			["B_FEM_FIA","Frauenkleidung",75],
			["B_FEM_NATO_long","Frauenkleidung",75],
			["B_FEM_NATO_Collar","Frauenkleidung",75],
			["B_FEM_NATO_Rolled","Frauenkleidung",75],
			["B_FEM_NATO","Frauenkleidung",75],
			
			["U_CDFOfficerUni_A",nil,50],
			["U_CDFSoldierUni_A",nil,50],
			
			["U_CombatUniVest_A",nil,50],
			["B_Fem_SPEC_Smith",nil,50],
			
			["U_B_CTRG_1",nil,50],
			["U_B_CTRG_2",nil,50],
			["U_B_CTRG_3",nil,50],
			
			["U_CombatUniLong_A",nil,50],
			["U_CombatUniLong_B",nil,50],
			["U_CombatUniFatigue_A",nil,50],

			["U_B_CombatUniform_mcam",nil,50],
			["U_I_CombatUniform_shortsleeve",nil,50],
			["U_I_CombatUniform",nil,50],
			["U_I_OfficerUniform",nil,50],
			
			["U_O_CombatUniform_ocamo",nil,50],
			["U_O_CombatUniform_oucamo",nil,50],
			
			["U_O_OfficerUniform_ocamo",nil,50],
			
			["U_O_PilotCoveralls",nil,50],
			["U_O_SpecopsUniform_ocamo",nil,50],
			["U_B_CombatUniform_mcam_vest",nil,50],
			
			["U_CombatUniShirt_A",nil,50],
			["rpima_uniform",nil,50],
			
			["U_TKOfficerUni_A",nil,50],
			["U_TKOfficerUni_B",nil,50],
			["U_TKSpecialUni_A",nil,50],
			["U_TKSpecialUni_B",nil,50],
			["U_TKSoldierUni_A",nil,50],
			["U_TKSoldierUni_B",nil,50],
			["TRYK_B_TRYK_3C_T",nil,50],
			
			["TRYK_ZARATAKI",nil,50],
			["TRYK_ZARATAKI2",nil,50],
			["TRYK_ZARATAKI3",nil,50],
			
			["TRYK_U_B_BLK","Biker-Jacke (Schwarz)",50],
			["TRYK_U_B_BLK_Tshirt","Biker-Jacke (Schwarz,kurz)",50],
			["TRYK_U_B_BLKBLK_CombatUniform","Biker-Kleidung (Schwarz)",50],
			["TRYK_U_B_BLKBLK_R_CombatUniform","Biker-Kleidung (Schwarz,kurz)",50],

			["U_IG_Guerilla1_1",nil,50],
			["U_I_G_Story_Protagonist_F",nil,50],
			["U_I_G_resistanceLeader_F",nil,50],
			["U_IG_leader","Guerilla Leader",50],

			["U_BG_Guerilla1_1",nil,50],
			["U_BG_Guerilla3_1",nil,50],
			["U_BG_Guerrilla_6_1",nil,50],
			["U_CivilianPilot_A",nil,50],
			
			["U_CombatOutdoor_A",nil,50],
			["U_CombatOutdoor_B",nil,50],
			["U_CombatOutdoor_C",nil,50],
			["U_CombatOutdoor_D",nil,50],
			["U_CDGCombatUni_A",nil,50],
			["U_CDGCombatUni_B",nil,50],
			["U_CDGCombatUni_C",nil,50],
			["U_CDGCombatUni_D",nil,50],
			["U_CivilianHunter_A",nil,50],
			["U_CivilianHunter_B",nil,50],
			["U_CivilianHunter_C",nil,50],
			["U_CivilianHunter_D",nil,50],
			["U_MilitiaUniTShirt_A",nil,50],
			["U_MilitiaUniTShirt_B",nil,50],
			["U_MilitiaUniTShirt_C",nil,50],
			["U_MilitiaUniTShirt_D",nil,50],
			["U_MilitiaUniTShirt_E",nil,50],
			["U_MilitiaUniTShirt_F",nil,50],
			["U_MilitiaUniTShirt_G",nil,50],
			["U_InsUniShirt_Leader",nil,50],
			["U_InsUniShirt_A",nil,50],
			["U_InsUniShirt_B",nil,50],
			["U_InsUniShirt_C",nil,50],
		
			["U_CombatUniLeadMerc_A",nil,50],
			["U_CombatUniLeadMerc_B",nil,50],
			["U_CombatUniLeadMerc_C",nil,50],
			["U_CombatUniLeadMerc_D",nil,50],
			["U_CombatUniLeadMerc_E",nil,50],
			["U_CombatUniLeadMerc_F",nil,50],
			["U_CombatUniShirtMercA_A",nil,50],
			["U_CombatUniShirtMercA_B",nil,50],
			["U_CombatUniShirtMercA_C",nil,50],
			["U_CombatUniShirtMercA_D",nil,50],
			["U_CombatUniShirtMercA_E",nil,50],
			["U_CombatUniShirtMercA_F",nil,50],
			["U_CombatUniShirtMercA_G",nil,50],
			// Cop Ausbilder["U_CombatUniShirtMercB_A",nil,50],
			["U_CombatUniShirtMercB_B",nil,50],
			["U_CombatUniShirtMercB_C",nil,50],
			["U_CombatUniShirtMercB_D",nil,50],
			["U_CombatUniShirtMercB_E",nil,50],
			["U_CombatUniShirtMercB_F",nil,50],
			["U_CombatUniShirtMercB_G",nil,50],
			["U_CombatUniShirtMercB_H",nil,50],
			["U_CombatUniShirtMercB_I",nil,50],
			["U_CombatUniShirtMercB_J",nil,50],
			["U_CombatUniShirtMercC_A",nil,50],
			["U_CombatUniShirtMercC_B",nil,50],
			["U_CombatUniShirtMercC_C",nil,50],
			["U_CombatUniShirtMercC_D",nil,50],
			["U_CombatUniShirtMercD_A",nil,50],
			["U_CombatUniShirtMercD_B",nil,50],
			["U_CombatUniShirtMercD_C",nil,50],
			["U_CombatUniShirtMercD_D",nil,50],
			["U_CombatUniShirtMercD_E",nil,50],
			["U_CombatUniShirtMercD_F",nil,50],
			["U_CombatUniShirtMercD_G",nil,50],
			
			["U_CivilianMetro_A",nil,50],
			["U_CivilianMetro_B",nil,50],
			["U_CivilianMetro_C",nil,50],
			["U_CivilianMetro_D",nil,50],
			["U_MilitiaSport_A",nil,50],
			["U_MilitiaSport_B",nil,50],
			["U_MilitiaSport_C",nil,50],
			["U_MilitiaUniShirt_A",nil,50],
			["U_MilitiaUniShirt_B",nil,50],
			["U_MilitiaUniShirt_C",nil,50],
			["U_MilitiaUniShirt_D",nil,50],
			["U_MilitiaUniShirt_E",nil,50],
			["U_MilitiaUniShirt_F",nil,50],
			["U_MilitiaUniShirt_G",nil,50],
			["U_CivilianOutdoor_A",nil,50],
			["U_CivilianOutdoor_B",nil,50],
			["U_CivilianOutdoor_C",nil,50],
			["U_CivilianOutdoor_D",nil,50],
			
			["U_CivilianSport_A",nil,50],
			["U_CivilianSport_B",nil,50],
			["U_CivilianSport_C",nil,50],
			["U_CivilianSport_D",nil,50],
			["U_TKLocalUniLong_A",nil,50],
			["U_TKLocalUniLong_B",nil,50],
			["U_TKLocalUniLong_C",nil,50],
			["U_TKLocalUniLong_D",nil,50],
			["U_TKLocalUniLong_E",nil,50],
			["U_DressTKLocalUni_A_A",nil,50],
			["U_DressTKLocalUni_A_B",nil,50],
			["U_DressTKLocalUni_A_C",nil,50],
			["U_DressTKLocalUni_A_D",nil,50],
			["U_DressTKLocalUni_A_E",nil,50],
			["U_DressTKLocalUni_B_A",nil,50],
			["U_DressTKLocalUni_B_B",nil,50],
			["U_DressTKLocalUni_B_C",nil,50],
			["U_DressTKLocalUni_B_D",nil,50],
			["U_DressTKLocalUni_B_E",nil,50],
			["U_DressTKLocalUni_C_A",nil,50],
			["U_DressTKLocalUni_C_B",nil,50],
			["U_DressTKLocalUni_C_C",nil,50],
			["U_DressTKLocalUni_C_D",nil,50],
			["U_DressTKLocalUni_C_E",nil,50],
			["U_DressTKLocalUni_D_A",nil,50],
			["U_DressTKLocalUni_D_B",nil,50],
			["U_DressTKLocalUni_D_C",nil,50],
			["U_DressTKLocalUni_D_D",nil,50],
			["U_DressTKLocalUni_D_E",nil,50],
			["U_DressTKLocalUni_E_A",nil,50],
			["U_DressTKLocalUni_E_B",nil,50],
			["U_DressTKLocalUni_E_C",nil,50],
			["U_DressTKLocalUni_E_D",nil,50],
			["U_DressTKLocalUni_E_E",nil,50],
			["U_TKLocalTactic_A",nil,50],
			["U_TKLocalTactic_B",nil,50],
			["U_TKLocalTactic_C",nil,50],
			["U_TKLocalTactic_D",nil,50],
			["U_TKLocalTactic_E",nil,50],			
			["U_TKLocalUni_A",nil,50],
			["U_TKLocalUni_B",nil,50],
			["U_TKLocalUni_C",nil,50],
			["U_TKLocalUni_D",nil,50],
			["U_TKLocalUni_E",nil,50],
			["U_TKLocalUni_F",nil,50],			
			["U_TKLocalCombat_A",nil,50],
			["U_TKLocalCombat_B",nil,50],
			["U_TKLocalCombat_C",nil,50],
			["U_TKLocalCombat_D",nil,50],
			["U_TKLocalCombat_E",nil,50],
			["U_TerrorCombat_A",nil,50],
			["U_TerrorCombat_B",nil,50],
			["U_TerrorCombat_Black",nil,50],
			
			["U_PMC_CombatUniformLS_BSGPBB",nil,50],
			["U_PMC_CombatUniformRS_BSGPBB",nil,50],
			["U_PMC_CombatUniformLS_BSGPSB",nil,50],
			["U_PMC_CombatUniformRS_BSGPSB",nil,50],
			["U_PMC_CombatUniformLS_BSSPBB",nil,50],
			["U_PMC_CombatUniformRS_BSSPBB",nil,50],
			["U_PMC_CombatUniformLS_BSSPSB",nil,50],
			["U_PMC_CombatUniformRS_BSSPSB",nil,50],
			["U_PMC_CombatUniformLS_GSBPBB",nil,50],
			["U_PMC_CombatUniformRS_GSBPBB",nil,50],
			["U_PMC_CombatUniformLS_GSSPBB",nil,50],
			["U_PMC_CombatUniformRS_GSSPBB",nil,50],
			["U_PMC_CombatUniformLS_SSBPBB",nil,50],
			["U_PMC_CombatUniformRS_SSBPBB",nil,50],
			["U_PMC_CombatUniformLS_SSGPBB",nil,50],
			["U_PMC_CombatUniformRS_SSGPBB",nil,50],
			["U_PMC_CombatUniformLS_SSGPSB",nil,50],
			["U_PMC_CombatUniformRS_SSGPSB",nil,50],
			["U_PMC_CombatUniformLS_ChckP_BPBB",nil,50],
			["U_PMC_CombatUniformRS_ChckP_BPBB",nil,50],
			["U_PMC_CombatUniformLS_ChckLR_SPBB",nil,50],
			["U_PMC_CombatUniformRS_ChckLR_SPBB",nil,50],
			["U_PMC_CombatUniformLS_ChckLB_GPBB",nil,50],
			["U_PMC_CombatUniformRS_ChckLB_GPBB",nil,50],
			["U_PMC_CombatUniformLS_ChckDBS_GPSB",nil,50],
			["U_PMC_CombatUniformRS_ChckDBS_GPSB",nil,50],
			["U_PMC_CombatUniformLS_IndPBSBB",nil,50],
			["U_PMC_CombatUniformRS_IndPBSBB",nil,50],
			
			["U_PMC_BluePlaidShirt_BeigeCords",nil,50],
			["U_PMC_BluTShirt_SJeans",nil,50],
			["U_PMC_BluPolo_BgPants",nil,50],
			["U_PMC_BluPolo_GrnPants",nil,50],
			["U_PMC_BrnPolo_BgPants",nil,50],
			["U_PMC_BrnPolo_BluPants",nil,50],
			["U_PMC_BlkTShirt_SJeans",nil,50],
			["U_PMC_BlkTShirt_DJeans",nil,50],
			["U_PMC_BlackPoloShirt_BeigeCords",nil,50],
			["U_PMC_BlckPolo_BluPants",nil,50],
			["U_PMC_BlckPolo_BgPants",nil,50],
			["U_PMC_BgPolo_GrnPants",nil,50],
			["U_PMC_WTShirt_DJeans",nil,50],
			["U_PMC_WhtPolo_BgPants",nil,50],
			["U_PMC_WhtPolo_BluPants",nil,50],
			["U_PMC_WhtPolo_GrnPants",nil,50],
			["U_PMC_RedPlaidShirt_DenimCords",nil,50],
			["U_PMC_GrnPolo_BgPants",nil,50],
			["U_PMC_GTShirt_DJeans",nil,50],
			["U_PMC_GTShirt_SJeans",nil,50],

			["TRYK_hoodie_3c",nil,50],
			["TRYK_hoodie_Blk",nil,50],
			["TRYK_hoodie_FR",nil,50],
			["TRYK_hoodie_Wood",nil,50],	
			
			["TRYK_OVERALL_SAGE_BLKboots_nk",nil,50],
			["TRYK_OVERALL_SAGE_BLKboots_nk_blk",nil,50],
			["TRYK_OVERALL_SAGE_BLKboots_nk_blk2",nil,50],
			["TRYK_OVERALL_flesh",nil,50],
			["TRYK_OVERALL_nok_flesh",nil,50],
			["TRYK_OVERALL_SAGE",nil,50],
			["TRYK_OVERALL_SAGE_BLKboots",nil,50],

			["TRYK_HRP_khk",nil,50],
			["TRYK_HRP_UCP",nil,50],
			["TRYK_HRP_USMC",nil,50],
			["TRYK_DMARPAT_T",nil,50],
			["TRYK_C_AOR2_T",nil,50],
			["TRYK_T_BLK_PAD",nil,50],
			["TRYK_T_CSAT_PAD",nil,50],
			["TRYK_T_OD_PAD",nil,50],
			["TRYK_T_PAD",nil,50],
			["TRYK_T_T2_PAD",nil,50],
			["TRYK_T_TAN_PAD",nil,50],
			["TRYK_T_camo_3c",nil,50],
			["TRYK_T_camo_3c_BG",nil,50],
			["TRYK_T_camo_Wood",nil,50],
			["TRYK_T_camo_Wood_BG",nil,50],
			["TRYK_T_camo_wood_marpat",nil,50],
			["TRYK_T_camo_wood_marpat_BG",nil,50],
			["TRYK_T_camo_Desert_marpat",nil,50],
			["TRYK_T_camo_desert_marpat_BG",nil,50],
			["TRYK_T_camo_tan",nil,50],
			["TRYK_B_USMC_R",nil,50],
			["TRYK_B_USMC_R_ROLL",nil,50],
			["TRYK_B_TRYK_MTP_T",nil,50],
			["TRYK_B_TRYK_OCP_T",nil,50],
			["TRYK_B_TRYK_OCP_D_T",nil,50],
			["TRYK_B_TRYK_UCP_T",nil,50],
			["TRYK_U_pad_hood_Blk",nil,50],
			["TRYK_U_pad_hood_Blod",nil,50],
			["TRYK_U_pad_hood_BKT2",nil,50],
			["TRYK_U_pad_hood_Cl",nil,50],
			["TRYK_U_pad_hood_Cl_blk",nil,50],
			["TRYK_U_pad_hood_CSATBlk",nil,50],
			["TRYK_U_pad_hood_odBK",nil,50],
			["TRYK_U_pad_hood_tan",nil,50],
			["TRYK_U_nohoodPcu_gry",nil,50],
			["TRYK_U_hood_mc",nil,50],
			["TRYK_U_hood_nc",nil,50],
			["TRYK_U_denim_hood_3c",nil,50],
			["TRYK_U_denim_hood_blk",nil,50],
			["TRYK_U_denim_hood_mc",nil,50],
			["TRYK_U_denim_hood_nc",nil,50],
			["TRYK_U_denim_jersey_blk",nil,50],
			["TRYK_U_denim_jersey_blu",nil,50],
			["TRYK_U_pad_j",nil,50],

			["TRYK_U_pad_j_blk",nil,50],
			["TRYK_U_taki_BL",nil,50],
			["TRYK_U_taki_G_BL",nil,50],
			["TRYK_U_taki_BLK",nil,50],
			["TRYK_U_taki_G_BLK",nil,50],
			["TRYK_U_taki_COY",nil,50],
			["TRYK_U_taki_G_COY",nil,50],
			["TRYK_U_taki_wh",nil,50],
			["TRYK_U_taki_G_WH",nil,50],
			["TRYK_U_Bts_PCUs",nil,50],
			["TRYK_U_Bts_PCUGs",nil,50],
			["TRYK_U_Bts_PCUODs",nil,50],
			["TRYK_U_Bts_GRYGRY_PCUs",nil,50],
			["TRYK_U_Bts_UCP_PCUs",nil,50],
			["TRYK_U_Bts_Wood_PCUs",nil,50],
			["TRYK_U_B_ACU",nil,50],
			["TRYK_U_B_ACUTshirt",nil,50],
			["TRYK_U_B_ARO1_CombatUniform",nil,50],
			["TRYK_U_B_ARO1R_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_BLK_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_BLK_R_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_CBR_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_CBR_R_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_GR_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_GR_R_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_GRY_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_GRY_R_CombatUniform",nil,50],
			["TRYK_U_B_ARO2_CombatUniform",nil,50],
			["TRYK_U_B_ARO2R_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_BLK_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_BLK_R_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_GRY_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_GRY_R_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_OD_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_OD_R_CombatUniform",nil,50],
			["TRYK_U_B_BLOD_T",nil,50],
			["TRYK_U_B_BLTAN_T",nil,50],
			["TRYK_U_B_BLKTAN_CombatUniform",nil,50],
			["TRYK_U_B_BLKTANR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_BLKOCP_CombatUniform",nil,50],
			["TRYK_U_B_BLKOCP_R_CombatUniformTshirt",nil,50],
			["TRYK_U_B_C01_Tsirt",nil,50],
			["TRYK_U_B_C02_Tsirt",nil,50],
			["TRYK_U_B_3c",nil,50],
			["TRYK_U_B_3cr",nil,50],
			["TRYK_U_B_BLK3CD",nil,50],
			["TRYK_U_B_BLK3CD_Tshirt",nil,50],
			["TRYK_U_B_BLKTAN",nil,50],
			["TRYK_U_B_BLKTAN_Tshirt",nil,50],
			["TRYK_U_B_BLK_OD",nil,50],
			["TRYK_U_B_BLK_OD_Tshirt",nil,50],
			["TRYK_U_B_OD_BLK",nil,50],
			["TRYK_U_B_OD_BLK_2",nil,50],
			["TRYK_U_B_ODTAN_Tshirt",nil,50],
			["TRYK_U_B_Sage_T",nil,50],
			["TRYK_U_B_Sage_Tshirt",nil,50],
			["TRYK_U_B_BLK_TAN_1",nil,50],
			["TRYK_U_B_BLK_TAN_2",nil,50],
			["TRYK_U_B_3CD_Delta_BDU",nil,50],
			["TRYK_U_B_3CD_Delta_BDUTshirt",nil,50],
			["TRYK_U_B_3CD_Ranger_BDU",nil,50],
			["TRYK_U_B_3CD_Ranger_BDUTshirt",nil,50],
			["TRYK_U_B_3CD_BLK_BDUTshirt",nil,50],
			["TRYK_U_B_3CD_BLK_BDUTshirt2",nil,50],
			["TRYK_U_B_fleece",nil,50],
			["TRYK_U_B_fleece_UCP",nil,50],
			["TRYK_U_B_GRTAN_CombatUniform",nil,50],
			["TRYK_U_B_GRTANR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_GRYOCP_CombatUniform",nil,50],
			["TRYK_U_B_GRYOCP_R_CombatUniformTshirt",nil,50],
			["TRYK_U_B_MARPAT_Desert",nil,50],
			["TRYK_U_B_MARPAT_Desert_Tshirt",nil,50],
			["TRYK_U_B_MARPAT_Desert2",nil,50],
			["TRYK_U_B_MARPAT_Desert2_Tshirt",nil,50],
			["TRYK_U_B_MARPAT_Wood",nil,50],
			["TRYK_U_B_MARPAT_Wood_Tshirt",nil,50],
			["TRYK_U_B_MARPAT_WOOD_CombatUniform",nil,50],
			["TRYK_U_B_MARPAT_WOOD_CombatUniformTshirt",nil,50],
			["TRYK_U_B_MTP_CombatUniform",nil,50],
			["TRYK_U_B_MTP_R_CombatUniform",nil,50],
			["TRYK_U_B_MTP_BLK_CombatUniform",nil,50],
			["TRYK_U_B_MTP_BLK_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCPD_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCPD_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_BLK_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_c_BLK_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_BLK_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_BLK_c_R_CombatUniform",nil,50],
			["TRYK_U_B_OD_OD_CombatUniform",nil,50],
			["TRYK_U_B_OD_OD_R_CombatUniform",nil,50],
			["TRYK_U_B_ODTAN_CombatUniform",nil,50],
			["TRYK_U_B_ODTANR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_PCUs",nil,50],
			["TRYK_U_B_PCUs_R",nil,50],
			["TRYK_U_B_PCUGs",nil,50],
			["TRYK_U_B_PCUGs_BLK",nil,50],
			["TRYK_U_B_PCUGs_BLK_R",nil,50],
			["TRYK_U_B_PCUGs_gry",nil,50],
			["TRYK_U_B_PCUGs_gry_R",nil,50],
			["TRYK_U_B_PCUGHs",nil,50],
			["TRYK_U_B_PCUODHs",nil,50],
			["TRYK_U_B_GRY_PCUs",nil,50],
			["TRYK_U_B_GRY_PCUs_R",nil,50],
			["TRYK_U_B_UCP_PCUs",nil,50],
			["TRYK_U_B_UCP_PCUs_R",nil,50],
			["TRYK_U_B_Wood_PCUs",nil,50],
			["TRYK_U_B_Wood_PCUs_R",nil,50],
			["TRYK_U_B_PCUODs",nil,50],
			["TRYK_U_B_PCUGs_OD",nil,50],
			["TRYK_U_B_PCUGs_OD_R",nil,50],
			["TRYK_U_B_AOR1_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_BLK_OD_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_BLK_tan_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_wh_blk_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_wh_OD_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_wh_tan_Rollup_CombatUniform",nil,50],
			
			["TRYK_U_B_Snowt",nil,50],
			["TRYK_U_B_Snow_CombatUniform",nil,50],
			["TRYK_U_B_woodtan_CombatUniform",nil,50],
			["TRYK_U_B_woodtanR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_TANOCP_CombatUniform",nil,50],
			["TRYK_U_B_TANOCP_R_CombatUniformTshirt",nil,50],
			["TRYK_U_B_TANTAN_CombatUniform",nil,50],
			["TRYK_U_B_TANTAN_R_CombatUniform",nil,50],
			["TRYK_U_B_JSDF_CombatUniform",nil,50],
			["TRYK_U_B_JSDF_CombatUniformTshirt",nil,50],
			["TRYK_U_B_NATO_UCP_CombatUniform",nil,50],
			["TRYK_U_B_NATO_UCP_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_UCP_GRY_CombatUniform",nil,50],
			["TRYK_U_B_NATO_UCP_GRY_R_CombatUniform",nil,50],
			["TRYK_U_B_PCUHs",nil,50],
			["TRYK_U_B_PCUHsW",nil,50],
			["TRYK_U_B_PCUHsW2",nil,50],
			["TRYK_U_B_PCUHsW3",nil,50],
			["TRYK_U_B_PCUHsW3nh",nil,50],
			["TRYK_U_B_PCUHsW4",nil,50],
			["TRYK_U_B_PCUHsW5",nil,50],
			["TRYK_U_B_PCUHsW6",nil,50],
			["TRYK_U_B_Woodland",nil,50],
			["TRYK_U_B_Woodland_Tshirt",nil,50],
			["TRYK_U_B_wood_CombatUniform",nil,50],
			["TRYK_U_B_woodR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_WDL_GRY_CombatUniform",nil,50],
			["TRYK_U_B_WDL_GRY_R_CombatUniform",nil,50],
			["TRYK_U_B_Wood_T",nil,50],
			["TRYK_U_B_wood3c_CombatUniform",nil,50],
			["TRYK_U_B_wood3c_CombatUniformTshirt",nil,50],
			["TRYK_U_B_WOOD_MARPAT_CombatUniform",nil,50],
			["TRYK_U_B_WOOD_MARPAT_CombatUniformTshirt",nil,50],
			
			["U_GhillieSuit_A",nil,150],
			["U_I_GhillieSuit",nil,150],
			["U_GhillieSuit_C",nil,150],
			["U_O_GhillieSuit",nil,150],
			["U_GhillieSuit_E",nil,150],
			["U_B_GhillieSuit",nil,150],
			["U_I_FullGhillie_ard","Vollst. Ghillie (Trocken)",200],
			["U_I_FullGhillie_sard","Wookie-Anzug (Halbtrocken)",200],
			["U_I_FullGhillie_lsh","Wookie-Anzug (Grün)",200]
		];
	};
	
	//Hats
	case 1:
	{
		[
			["H_Hat_Face_Wrap",nil,25],
			["H_Hat_Face_Wrap_Desert",nil,25],
			["H_Hat_Face_Wrap_Olive",nil,25],
			["H_Hat_Face_Wrap_Red",nil,25],
			
			["H_Hat_Face_Wrap_Dark","Shemag G. Schwarz",25],
			["H_Hat_Face_Wrap_DPM","Shemag G. Tarn",25],
			
			["H_Hat_Kufiya_B",nil,25],
			["H_Hat_Kufiya_F",nil,25],
			["H_Hat_Kufiya_D",nil,25],
			["H_Hat_Kufiya_C",nil,25],
			["H_Hat_Kufiya",nil,25],
			["H_Hat_Kufiya_G",nil,25],
			["H_Hat_Kufiya_R",nil,25],
			
			["H_ShemagOpen_tan",nil,25],
			["H_Shemag_olive",nil,25],
			["H_ShemagOpen_khk",nil,25],
			
			["H_HelmetO_ocamo",nil,25],
			["H_MilCap_oucamo",nil,25],
			["H_Bandanna_camo",nil,25],
			
			["H_Hat_Face_Balaclava_T",nil,25],
			["H_Hat_Face_Wrap_Black",nil,25],
			["H_Hat_Face_Wrap_Gold",nil,25],
	
			["H_Hat_Face_Wrap_Dark",nil,25],
			["H_Hat_Face_Wrap_White",nil,25],
			["H_Hat_Face_Wrap_DPM",nil,25],
			["H_Hat_Face_Wrap_Flecktarn",nil,25],
			["H_Hat_Face_Wrap_Sand",nil,25],
			
			["H_ALFR_Metal_Facemask_gry",nil,25],
			["H_ALFR_Metal_Facemask_oli",nil,25],
			["H_ALFR_Metal_Facemask_sand",nil,25],
			["H_ALFR_Metal_Facemask_blk",nil,25],
			
			["H_ALFR_Metal_Gasmask_RU_fuckyou",nil,25],
			["H_ALFR_Metal_Gasmask_RU_grey",nil,25],
			["H_ALFR_Metal_Gasmask_RU_khk",nil,25],
			["H_ALFR_Metal_Gasmask_RU_oli",nil,25],
			["H_ALFR_Metal_Gasmask_RU_blk",nil,25],
			["H_ALFR_Gasmask",nil,25],
			
			["H_Hat_Face_Cover_Black",nil,25],
			["H_Hat_Face_Cover_Gold",nil,25],
			["H_Hat_Face_Cover_Green",nil,25],
			
			["kio_skl_msk_weed",nil,25],
			["kio_skl_msk_UK",nil,25],
			["kio_skl_msk_US",nil,25],
			["kio_skl_msk_scot",nil,25],
			["kio_skl_msk_redranger",nil,25],
			["kio_skl_msk_p",nil,25],
			["kio_skl_msk_pun",nil,25],
			["kio_skl_msk_o",nil,25],
			["kio_skl_msk_nirish",nil,25],
			["kio_skl_msk_irish",nil,25],
			["kio_skl_msk_grey",nil,25],
			["kio_skl_msk_german",nil,25],
			["kio_skl_msk_GOW",nil,25],
			["kio_skl_msk_frost",nil,25],
			["kio_skl_msk_fran",nil,25],
			["kio_skl_msk_fire",nil,25],
			["kio_skl_msk_black",nil,25],
			["kio_skl_msk_blood",nil,25],
			["kio_skl_msk_can",nil,25],
			["kio_skl_msk",nil,25],
			["kio_skl_msk_red",nil,25],
			["kio_skl_msk_grn",nil,25]
			
		];
	};
	
	//Glasses
	case 2:
	{
		[		
			["A3L_Balaclava",nil,15],
			["Balaclava_Black",nil,15],
			["Balaclava_GRY",nil,15],
			["Balaclava_OD",nil,15],
			["T_HoodACUCLR",nil,15],
			["T_HoodBDUCLR",nil,15],
			["T_HoodBlkCLR",nil,15],
			["T_HoodMDCLR",nil,15],
			["T_HoodODCLR",nil,15],
			["T_HoodTanCLR",nil,15],
			["T_HoodMWCLR",nil,15],
			
			["Shemagh_FaceGry",nil,15],
			["Shemagh_FaceOD",nil,15],
			["Shemagh_FaceRed",nil,15],
			["Shemagh_FaceTan",nil,15],
			["Shemagh_Face",nil,15],
			
			["G_Balaclava_blk",nil,15],
			
			["PU_shemagh_GryO",nil,15],
			["PU_shemagh_ODO",nil,15],
			["PU_shemagh_TanO",nil,15],
			["PU_shemagh_WhiteO",nil,15],
			
			["SAS_shemagh_OD",nil,15],
			["SAS_shemagh_Tan",nil,15],
			["SAS_shemagh_White",nil,15],
			
			["Mask_M40",nil,15],
			["Mask_M40_OD",nil,15],
			["Mask_M50",nil,15]
		];
	};
	
	//Vest
	case 3:
	{
		[
			["V_PlateCarrierInd_PMC_blk",nil,300], 
			["V_PlateCarrierInd_PMC_grn",nil,300], 
			["V_PlateCarrierIA1_dgtl",nil,150], 
			["V_PlateCarrierIA2_dgtl",nil,300], 
		//	["V_PlateCarrier_light_digiCamo",nil,150], 
		//	["V_PlateCarrier_heavy_digiCamo",nil,300], 
			["TRYK_V_PlateCarrier_coyo_L",nil,150], 
			["TRYK_V_PlateCarrier_coyo",nil,300], 
			["TRYK_V_PlateCarrier_ACU_L",nil,150], 
			["TRYK_V_PlateCarrier_ACU",nil,300], 
			["TRYK_V_PlateCarrier_wood_L",nil,150], 
			["TRYK_V_PlateCarrier_wood",nil,300], 
			["TRYK_V_PlateCarrier_JSDF",nil,300], 
			["Jamie_Rebell","Fuck U Police",300], 

			["V_TacVest_darkblck",nil,150], 
			
			["k_cut_1","Sinister Sons",150], 
			["k_cut_2","Gold Gunners",150], 
			["k_cut_3","Sons of Anarchy Mitglied",150], 
			["k_cut_4","Sons of Anarchy Chef",150], 
			["k_cut_5","Sons of Outlaws",150], 
			
		//	["V_TacVest_TK",nil,150], 
			["V_TacVest_brn",nil,150], 
			["V_TacVest_khk",nil,150], 
			["V_TacVest_oli",nil,150], 
			["V_TacVest_blk",nil,150], 
			["V_I_G_resistanceLeader_F",nil,150], 
			["V_TacVest_camo",nil,150], 
			
		//	["V_PlateCarrier_heavy_A",nil,150], 
		//	["V_PlateCarrier_heavy_B",nil,150], 
		//	["V_PlateCarrier_heavy_C",nil,150], 
		//	["V_PlateCarrier_heavy_D",nil,150], 
		//	["V_PlateCarrier_heavy_E",nil,150], 
		//	["V_PlateCarrier_heavy_F",nil,150], 
			
		//	["V_FlakJacket_Black",nil,150], 
		//	["V_FlakJacket_KP_Black",nil,150], 
		//	["V_FlakJacket_digiCamo",nil,150], 
		//	["V_FlakJacket_KP_digiCamo",nil,150], 
		//	["V_FlakJacket_Green",nil,150], 
		//	["V_FlakJacket_KP_Green",nil,150], 
		//	["V_FlakJacket_Tan",nil,150],
		//	["V_FlakJacket_KP_Tan",nil,150],
		//	["V_FlakJacket_Woodland",nil,150],
		//	["V_FlakJacket_KP_Woodland",nil,150],
			
		//	["TRYK_V_tacSVD_BK",nil,150],
		//	["TRYK_V_tacSVD_OD",nil,150],
		//	["TRYK_V_tacv1LC_BK",nil,150],
		//	["TRYK_V_tacv1LC_CY",nil,150],
		//	["TRYK_V_tacv1LC_OD",nil,150],
			
			["TRYK_V_ArmorVest_Winter",nil,150]
		];
	};
	
	//Backpacks
	case 4:
	{
		[
			["domepokemon",nil,75],
			["domepony",nil,75],
			["domegraffiti",nil,75],
			["domebuhse",nil,75],
			["domekappa_s",nil,75],
			["domekappa_blau",nil,75],
			["domekappa_p",nil,75],
			["domekappa_t",nil,75],
			["domekappa_w",nil,75],
			["domeadi_s",nil,75],
			["domeadi_blau",nil,75],
			["domeadi_p",nil,75],
			["domeadi_t",nil,75],
			["domeadi_w",nil,75],
			["domenik_s",nil,75],
			["domenik_blau",nil,75],
			["domenik_p",nil,75],
			["domenik_t",nil,75],
			["domenik_w",nil,75],
			["domepu_s",nil,75],
			["domepu_blau",nil,75],
			["domepu_p",nil,75],
			["domepu_t",nil,75],
			["domepu_w",nil,75],
			["TRYK_B_Carryall_wood",nil,100],
			["TRYK_B_Carryall_wh",nil,100],
			["TRYK_B_Carryall_blk",nil,100],
			["TRYK_B_Carryall_JSDF",nil,100],
			["TRYK_B_Alicepack",nil,100],
			["B_Carryall_oucamo",nil,100],
			["B_Carryall_cbr",nil,100],
			["B_Carryall_ocamo",nil,100],
			["B_Carryall_mcamo",nil,100],
			["B_Carryall_oli",nil,100],
			["B_Carryall_khk",nil,100],
			["TRYK_B_tube_blk",nil,50],
			["TRYK_B_tube_cyt",nil,50],
			["TRYK_B_tube_od",nil,50],
			["ACE_TacticalLadder_Pack",nil,500],
			["B_Parachute",nil,500]
		];
	};
};