/*
	File: fn_clothing_fbi.sqf
	Author: Bryan "Tonic" Boardwine
	
	Description:
	Master configuration file for Bruce's Outback Outfits.
*/
#include <macro.h>
private["_filter"];
_filter = [_this,0,0,[0]] call BIS_fnc_param;
//Classname, Custom Display name (use nil for Cfg->DisplayName, price

//Shop Title Name
//ctrlSetText[3104,"FBI Clothing Shop"];

//If (__GETC__(life_donator) <= 3)exitwith{closeDialog 0; hint "Du bist nicht in der FBI Abteilung tätig (-Dlvl)"};
if(!license_cop_fbi)exitwith{closeDialog 0; hint "Du bist nicht in der FBI Abteilung tätig"};
if(playerSide != west) exitWith {closeDialog 0;};

switch (_filter) do
{
	//Uniform
	
		
	case 0:
	{
		[
		//Fbi
			["FBI_rang1","FBI Detective Kurz",10],
			["mr_pol_cloth_fbi_c_3","FBI Detective Lang",10],
			["FBI_rang2","FBI Sergeant Kurz",10],
			["mr_pol_cloth_fbi_c_4","FBI Sergeant Lang",10],
			["FBI_rang3","FBI 1st Sergeant Kurz",15],
			["mr_pol_cloth_fbi_c_5","FBI 1st Sergeant Lang",15],
			["FBI_rang4","FBI Lieutenant Kurz",15],
			["mr_pol_cloth_fbi_c_6","FBI Lieutenant Lang",15],
			["FBI_rang5","FBI 1st Lieutenant Kurz",20],
			["mr_pol_cloth_fbi_c_7","FBI 1st Lieutenant Lang",20],
			["FBI_rang6","FBI Captain Kurz",20],
			["mr_pol_cloth_fbi_c_8","FBI Captain Lang",20],
			["FBI_rang7","FBI Commander Kurz",25],
			["mr_pol_cloth_fbi_c_9","FBI Commander Lang",25],
			["FBI_rang8","FBI Dep. Chief Kurz",25],
			["mr_pol_cloth_fbi_c_10","FBI Dep. Chief Lang",25],
			["FBI_rang9","FBI Ast. Chief Kurz",30],
			["mr_pol_cloth_fbi_c_11","FBI Ast. Chief Lang",30],
			["FBI_rang10","FBI Chief Kurz",30],
			["mr_pol_cloth_fbi_c_12","FBI Chief Lang",30],
			["mr_pol_cloth_fbi_c_13","FBI Commissioner Lang",30],
			["TRYK_U_B_OD_OD_R_CombatUniform","Einsatzkleidung (Grün)",50],
		
		// Zivil
			["A3L_Bikini_Girl",nil,175],
			["U_BasicBodyICE123",nil,150],

			["A3L_Character_Uniform","Freizeitkleidung",100],
			["A3L_Dude_Outfit","Kollegah Outfit",100],
			["A3L_Farmer_Outfit","Bauernkleidung",75],
			["A3L_Priest_Uniform","Priester",75],
			["taxi_uni","Taxi Uniform",25],
			["A3L_Worker_Outfit","Arbeiterkleidung",50],
			["HI1",nil,25],
			["RastaCiv",nil,25],
			["vacationshirt_uni",nil,25],
			
			["TRYK_shirts_DENIM_BK",nil,25],
			["TRYK_shirts_DENIM_BK_Sleeve",nil,25],
			["TRYK_shirts_DENIM_BL",nil,25],
			["TRYK_shirts_DENIM_BL_Sleeve",nil,25],		
			["TRYK_shirts_DENIM_BWH",nil,25],
			["TRYK_shirts_DENIM_BWH_Sleeve",nil,25],			
			["TRYK_shirts_DENIM_R",nil,25],
			["TRYK_shirts_DENIM_R_Sleeve",nil,25],			
			["TRYK_shirts_DENIM_RED2",nil,25],
			["TRYK_shirts_DENIM_RED2_Sleeve",nil,25],			
			["TRYK_shirts_DENIM_WH",nil,25],
			["TRYK_shirts_DENIM_WH_Sleeve",nil,25],			
			["TRYK_shirts_DENIM_WHB",nil,25],
			["TRYK_shirts_DENIM_WHB_Sleeve",nil,25],		
			["TRYK_shirts_DENIM_ylb",nil,25],
			["TRYK_shirts_DENIM_ylb_Sleeve",nil,25],
			["TRYK_shirts_DENIM_od",nil,25],
			["TRYK_shirts_DENIM_od_Sleeve",nil,25],
			["TRYK_shirts_OD_PAD",nil,25],
			["TRYK_shirts_OD_PAD_BK",nil,25],
			["TRYK_shirts_OD_PAD_BL",nil,25],
			["TRYK_shirts_OD_PAD_BLW",nil,25],
			["TRYK_shirts_OD_PAD_BLU3",nil,25],
			["TRYK_shirts_OD_PAD_RED2",nil,25],
			["TRYK_shirts_OD_PAD_YEL",nil,25],
			["TRYK_shirts_BLK_PAD",nil,25],
			["TRYK_shirts_BLK_PAD_BK",nil,25],
			["TRYK_shirts_BLK_PAD_BL",nil,25],
			["TRYK_shirts_BLK_PAD_BLW",nil,25],
			["TRYK_shirts_BLK_PAD_BLU3",nil,25],
			["TRYK_shirts_BLK_PAD_RED2",nil,25],
			["TRYK_shirts_BLK_PAD_YEL",nil,25],
			["TRYK_shirts_PAD",nil,25],
			["TRYK_shirts_PAD_BK",nil,25],
			["TRYK_shirts_PAD_BL",nil,25],
			["TRYK_shirts_PAD_BLW",nil,25],
			["TRYK_shirts_PAD_RED2",nil,25],
			["TRYK_shirts_PAD_BLU3",nil,25],
			["TRYK_shirts_PAD_YEL",nil,25],
			["TRYK_shirts_TAN_PAD",nil,25],
			["TRYK_shirts_TAN_PAD_BK",nil,25],
			["TRYK_shirts_TAN_PAD_BL",nil,25],
			["TRYK_shirts_TAN_PAD_BLW",nil,25],			
			["TRYK_shirts_TAN_PAD_BLU3",nil,25],
			["TRYK_shirts_TAN_PAD_RED2",nil,25],
			["TRYK_shirts_TAN_PAD_YEL",nil,25],
			
			["TRYK_U_B_RED_T_BR",nil,25],
			["TRYK_U_B_RED_T_BG_BR",nil,25],
			["TRYK_U_B_BLK_T_BK",nil,25],
			["TRYK_U_B_BLK_T_BG_BK",nil,25],
			["TRYK_U_B_BLK_T_WH",nil,25],
			["TRYK_U_B_BLK_T_BG_WH",nil,25],
			["TRYK_U_B_Denim_T_BK",nil,25],
			["TRYK_U_B_Denim_T_BG_BK",nil,25],
			["TRYK_U_B_Denim_T_WH",nil,25],
			["TRYK_U_B_Denim_T_BG_WH",nil,25],
			
			["U_Rangemaster_A",nil,25],
			["U_Rangemaster_B",nil,25],
			["U_Rangemaster_C",nil,25],
			["U_Rangemaster_D",nil,25],
			["U_Rangemaster_E",nil,25],
			["U_Rangemaster_F",nil,25],
			["U_Rangemaster_G",nil,25],
			
			["U_CivilianTShirt_A",nil,25],
			["U_CivilianTShirt_B",nil,25],
			["U_CivilianTShirt_C",nil,25],
			["U_CivilianTShirt_D",nil,25],
			["U_CivilianTShirt_E",nil,25],
			["U_CivilianTShirt_F",nil,25],
			["U_CivilianTShirt_G",nil,25],
			
			["cg_awesome1",nil,25],
			["cg_bb1",nil,25],
			["cg_beats1",nil,25],
			["cg_burgerking1",nil,25],
			["cg_catvideos1",nil,25],
			["cg_condoms1",nil,25],
			["cg_csgo1",nil,25],
			["cg_dad1",nil,25],
			["cg_deeznuts1",nil,25],
			["cg_ea1",nil,25],
			["cg_et1",nil,25],
			["cg_evolution1",nil,25],
			["cg_ferrari1",nil,25],
			["cg_gameover1",nil,25],
			["cg_gamerepeat1",nil,25],
			["cg_got1",nil,25],
			["cg_hand1",nil,25],
			["cg_hearts1",nil,25],
			["cg_homer1",nil,25],
			["cg_illuminati1",nil,25],
			["cg_jason1",nil,25],
			["cg_joker1",nil,25],
			["cg_kfc1",nil,25],
			["cg_lambo1",nil,25],
			["cg_lego1",nil,25],
			["cg_loading1",nil,25],
			["cg_mario1",nil,25],
			["cg_mayan1",nil,25],
			["cg_mtv1",nil,25],
			["cg_nike1",nil,25],
			["cg_masterrace1",nil,25],
			["cg_peanut1",nil,25],
			["cg_pepsi1",nil,25],
			["cg_pika1",nil,25],
			["cg_steam1",nil,25],
			["cg_stoned1",nil,25],
			["cg_strippers1",nil,25],
			["cg_superman1",nil,25],
			["cg_taylorswift1",nil,25],
			["cg_turtles1",nil,25],
			["cg_upyours1",nil,25],
			["cg_wow1",nil,25],
			["cg_jounie1",nil,25],
			
		//Rebell
			["I_FEM_AAF_long","Frauenkleidung",75],
			["B_FEM_AAF_Rolled","Frauenkleidung",75],
			["I_FEM_AAF","Frauenkleidung",75],
			["O_FEM_CSAT_Long","Frauenkleidung",75],
			["O_FEM_CSAT_Rolled","Frauenkleidung",75],
			["O_FEM_CSAT","Frauenkleidung",75],
			["B_FEM_FIA","Frauenkleidung",75],
			["B_FEM_NATO_long","Frauenkleidung",75],
			["B_FEM_NATO_Collar","Frauenkleidung",75],
			["B_FEM_NATO_Rolled","Frauenkleidung",75],
			["B_FEM_NATO","Frauenkleidung",75],
			
			["U_CDFOfficerUni_A",nil,50],
			["U_CDFSoldierUni_A",nil,50],
			
			["U_CombatUniVest_A",nil,50],
			["B_Fem_SPEC_Smith",nil,50],
			
			["U_B_CTRG_1",nil,50],
			["U_B_CTRG_2",nil,50],
			["U_B_CTRG_3",nil,50],
			
			["U_CombatUniLong_A",nil,50],
			["U_CombatUniLong_B",nil,50],
			["U_CombatUniFatigue_A",nil,50],

			["U_B_CombatUniform_mcam",nil,50],
			["U_I_CombatUniform_shortsleeve",nil,50],
			["U_I_CombatUniform",nil,50],
			["U_I_OfficerUniform",nil,50],
			
			["U_O_CombatUniform_ocamo",nil,50],
			["U_O_CombatUniform_oucamo",nil,50],
			
			["U_O_OfficerUniform_ocamo",nil,50],
			
			["U_O_PilotCoveralls",nil,50],
			["U_O_SpecopsUniform_ocamo",nil,50],
			["U_B_CombatUniform_mcam_vest",nil,50],
			
			["U_CombatUniShirt_A",nil,50],
			["rpima_uniform",nil,50],
			
			["U_TKOfficerUni_A",nil,50],
			["U_TKOfficerUni_B",nil,50],
			["U_TKSpecialUni_A",nil,50],
			["U_TKSpecialUni_B",nil,50],
			["U_TKSoldierUni_A",nil,50],
			["U_TKSoldierUni_B",nil,50],
			["TRYK_B_TRYK_3C_T",nil,50],
			
			["TRYK_ZARATAKI",nil,50],
			["TRYK_ZARATAKI2",nil,50],
			["TRYK_ZARATAKI3",nil,50],
			
			["TRYK_U_B_BLK","Biker-Jacke (Schwarz)",50],
			["TRYK_U_B_BLK_Tshirt","Biker-Jacke (Schwarz,kurz)",50],
			["TRYK_U_B_BLKBLK_CombatUniform","Biker-Kleidung (Schwarz)",50],
			["TRYK_U_B_BLKBLK_R_CombatUniform","Biker-Kleidung (Schwarz,kurz)",50],

			["U_IG_Guerilla1_1",nil,50],
			["U_I_G_Story_Protagonist_F",nil,50],
			["U_I_G_resistanceLeader_F",nil,50],
			["U_IG_leader","Guerilla Leader",50],

			["U_BG_Guerilla1_1",nil,50],
			["U_BG_Guerilla3_1",nil,50],
			["U_BG_Guerrilla_6_1",nil,50],
			["U_CivilianPilot_A",nil,50],
			
			["U_CombatOutdoor_A",nil,50],
			["U_CombatOutdoor_B",nil,50],
			["U_CombatOutdoor_C",nil,50],
			["U_CombatOutdoor_D",nil,50],
			["U_CDGCombatUni_A",nil,50],
			["U_CDGCombatUni_B",nil,50],
			["U_CDGCombatUni_C",nil,50],
			["U_CDGCombatUni_D",nil,50],
			["U_CivilianHunter_A",nil,50],
			["U_CivilianHunter_B",nil,50],
			["U_CivilianHunter_C",nil,50],
			["U_CivilianHunter_D",nil,50],
			["U_MilitiaUniTShirt_A",nil,50],
			["U_MilitiaUniTShirt_B",nil,50],
			["U_MilitiaUniTShirt_C",nil,50],
			["U_MilitiaUniTShirt_D",nil,50],
			["U_MilitiaUniTShirt_E",nil,50],
			["U_MilitiaUniTShirt_F",nil,50],
			["U_MilitiaUniTShirt_G",nil,50],
			["U_InsUniShirt_Leader",nil,50],
			["U_InsUniShirt_A",nil,50],
			["U_InsUniShirt_B",nil,50],
			["U_InsUniShirt_C",nil,50],
		
			["U_CombatUniLeadMerc_A",nil,50],
			["U_CombatUniLeadMerc_B",nil,50],
			["U_CombatUniLeadMerc_C",nil,50],
			["U_CombatUniLeadMerc_D",nil,50],
			["U_CombatUniLeadMerc_E",nil,50],
			["U_CombatUniLeadMerc_F",nil,50],
			["U_CombatUniShirtMercA_A",nil,50],
			["U_CombatUniShirtMercA_B",nil,50],
			["U_CombatUniShirtMercA_C",nil,50],
			["U_CombatUniShirtMercA_D",nil,50],
			["U_CombatUniShirtMercA_E",nil,50],
			["U_CombatUniShirtMercA_F",nil,50],
			["U_CombatUniShirtMercA_G",nil,50],
			// Cop Ausbilder["U_CombatUniShirtMercB_A",nil,50],
			["U_CombatUniShirtMercB_B",nil,50],
			["U_CombatUniShirtMercB_C",nil,50],
			["U_CombatUniShirtMercB_D",nil,50],
			["U_CombatUniShirtMercB_E",nil,50],
			["U_CombatUniShirtMercB_F",nil,50],
			["U_CombatUniShirtMercB_G",nil,50],
			["U_CombatUniShirtMercB_H",nil,50],
			["U_CombatUniShirtMercB_I",nil,50],
			["U_CombatUniShirtMercB_J",nil,50],
			["U_CombatUniShirtMercC_A",nil,50],
			["U_CombatUniShirtMercC_B",nil,50],
			["U_CombatUniShirtMercC_C",nil,50],
			["U_CombatUniShirtMercC_D",nil,50],
			["U_CombatUniShirtMercD_A",nil,50],
			["U_CombatUniShirtMercD_B",nil,50],
			["U_CombatUniShirtMercD_C",nil,50],
			["U_CombatUniShirtMercD_D",nil,50],
			["U_CombatUniShirtMercD_E",nil,50],
			["U_CombatUniShirtMercD_F",nil,50],
			["U_CombatUniShirtMercD_G",nil,50],
			
			["U_CivilianMetro_A",nil,50],
			["U_CivilianMetro_B",nil,50],
			["U_CivilianMetro_C",nil,50],
			["U_CivilianMetro_D",nil,50],
			["U_MilitiaSport_A",nil,50],
			["U_MilitiaSport_B",nil,50],
			["U_MilitiaSport_C",nil,50],
			["U_MilitiaUniShirt_A",nil,50],
			["U_MilitiaUniShirt_B",nil,50],
			["U_MilitiaUniShirt_C",nil,50],
			["U_MilitiaUniShirt_D",nil,50],
			["U_MilitiaUniShirt_E",nil,50],
			["U_MilitiaUniShirt_F",nil,50],
			["U_MilitiaUniShirt_G",nil,50],
			["U_CivilianOutdoor_A",nil,50],
			["U_CivilianOutdoor_B",nil,50],
			["U_CivilianOutdoor_C",nil,50],
			["U_CivilianOutdoor_D",nil,50],
			
			["U_CivilianSport_A",nil,50],
			["U_CivilianSport_B",nil,50],
			["U_CivilianSport_C",nil,50],
			["U_CivilianSport_D",nil,50],
			["U_TKLocalUniLong_A",nil,50],
			["U_TKLocalUniLong_B",nil,50],
			["U_TKLocalUniLong_C",nil,50],
			["U_TKLocalUniLong_D",nil,50],
			["U_TKLocalUniLong_E",nil,50],
			["U_DressTKLocalUni_A_A",nil,50],
			["U_DressTKLocalUni_A_B",nil,50],
			["U_DressTKLocalUni_A_C",nil,50],
			["U_DressTKLocalUni_A_D",nil,50],
			["U_DressTKLocalUni_A_E",nil,50],
			["U_DressTKLocalUni_B_A",nil,50],
			["U_DressTKLocalUni_B_B",nil,50],
			["U_DressTKLocalUni_B_C",nil,50],
			["U_DressTKLocalUni_B_D",nil,50],
			["U_DressTKLocalUni_B_E",nil,50],
			["U_DressTKLocalUni_C_A",nil,50],
			["U_DressTKLocalUni_C_B",nil,50],
			["U_DressTKLocalUni_C_C",nil,50],
			["U_DressTKLocalUni_C_D",nil,50],
			["U_DressTKLocalUni_C_E",nil,50],
			["U_DressTKLocalUni_D_A",nil,50],
			["U_DressTKLocalUni_D_B",nil,50],
			["U_DressTKLocalUni_D_C",nil,50],
			["U_DressTKLocalUni_D_D",nil,50],
			["U_DressTKLocalUni_D_E",nil,50],
			["U_DressTKLocalUni_E_A",nil,50],
			["U_DressTKLocalUni_E_B",nil,50],
			["U_DressTKLocalUni_E_C",nil,50],
			["U_DressTKLocalUni_E_D",nil,50],
			["U_DressTKLocalUni_E_E",nil,50],
			["U_TKLocalTactic_A",nil,50],
			["U_TKLocalTactic_B",nil,50],
			["U_TKLocalTactic_C",nil,50],
			["U_TKLocalTactic_D",nil,50],
			["U_TKLocalTactic_E",nil,50],			
			["U_TKLocalUni_A",nil,50],
			["U_TKLocalUni_B",nil,50],
			["U_TKLocalUni_C",nil,50],
			["U_TKLocalUni_D",nil,50],
			["U_TKLocalUni_E",nil,50],
			["U_TKLocalUni_F",nil,50],			
			["U_TKLocalCombat_A",nil,50],
			["U_TKLocalCombat_B",nil,50],
			["U_TKLocalCombat_C",nil,50],
			["U_TKLocalCombat_D",nil,50],
			["U_TKLocalCombat_E",nil,50],
			["U_TerrorCombat_A",nil,50],
			["U_TerrorCombat_B",nil,50],
			["U_TerrorCombat_Black",nil,50],
			
			["U_PMC_CombatUniformLS_BSGPBB",nil,50],
			["U_PMC_CombatUniformRS_BSGPBB",nil,50],
			["U_PMC_CombatUniformLS_BSGPSB",nil,50],
			["U_PMC_CombatUniformRS_BSGPSB",nil,50],
			["U_PMC_CombatUniformLS_BSSPBB",nil,50],
			["U_PMC_CombatUniformRS_BSSPBB",nil,50],
			["U_PMC_CombatUniformLS_BSSPSB",nil,50],
			["U_PMC_CombatUniformRS_BSSPSB",nil,50],
			["U_PMC_CombatUniformLS_GSBPBB",nil,50],
			["U_PMC_CombatUniformRS_GSBPBB",nil,50],
			["U_PMC_CombatUniformLS_GSSPBB",nil,50],
			["U_PMC_CombatUniformRS_GSSPBB",nil,50],
			["U_PMC_CombatUniformLS_SSBPBB",nil,50],
			["U_PMC_CombatUniformRS_SSBPBB",nil,50],
			["U_PMC_CombatUniformLS_SSGPBB",nil,50],
			["U_PMC_CombatUniformRS_SSGPBB",nil,50],
			["U_PMC_CombatUniformLS_SSGPSB",nil,50],
			["U_PMC_CombatUniformRS_SSGPSB",nil,50],
			["U_PMC_CombatUniformLS_ChckP_BPBB",nil,50],
			["U_PMC_CombatUniformRS_ChckP_BPBB",nil,50],
			["U_PMC_CombatUniformLS_ChckLR_SPBB",nil,50],
			["U_PMC_CombatUniformRS_ChckLR_SPBB",nil,50],
			["U_PMC_CombatUniformLS_ChckLB_GPBB",nil,50],
			["U_PMC_CombatUniformRS_ChckLB_GPBB",nil,50],
			["U_PMC_CombatUniformLS_ChckDBS_GPSB",nil,50],
			["U_PMC_CombatUniformRS_ChckDBS_GPSB",nil,50],
			["U_PMC_CombatUniformLS_IndPBSBB",nil,50],
			["U_PMC_CombatUniformRS_IndPBSBB",nil,50],
			
			["U_PMC_BluePlaidShirt_BeigeCords",nil,50],
			["U_PMC_BluTShirt_SJeans",nil,50],
			["U_PMC_BluPolo_BgPants",nil,50],
			["U_PMC_BluPolo_GrnPants",nil,50],
			["U_PMC_BrnPolo_BgPants",nil,50],
			["U_PMC_BrnPolo_BluPants",nil,50],
			["U_PMC_BlkTShirt_SJeans",nil,50],
			["U_PMC_BlkTShirt_DJeans",nil,50],
			["U_PMC_BlackPoloShirt_BeigeCords",nil,50],
			["U_PMC_BlckPolo_BluPants",nil,50],
			["U_PMC_BlckPolo_BgPants",nil,50],
			["U_PMC_BgPolo_GrnPants",nil,50],
			["U_PMC_WTShirt_DJeans",nil,50],
			["U_PMC_WhtPolo_BgPants",nil,50],
			["U_PMC_WhtPolo_BluPants",nil,50],
			["U_PMC_WhtPolo_GrnPants",nil,50],
			["U_PMC_RedPlaidShirt_DenimCords",nil,50],
			["U_PMC_GrnPolo_BgPants",nil,50],
			["U_PMC_GTShirt_DJeans",nil,50],
			["U_PMC_GTShirt_SJeans",nil,50],

			["TRYK_hoodie_3c",nil,50],
			["TRYK_hoodie_Blk",nil,50],
			["TRYK_hoodie_FR",nil,50],
			["TRYK_hoodie_Wood",nil,50],	
			
			["TRYK_OVERALL_SAGE_BLKboots_nk",nil,50],
			["TRYK_OVERALL_SAGE_BLKboots_nk_blk",nil,50],
			["TRYK_OVERALL_SAGE_BLKboots_nk_blk2",nil,50],
			["TRYK_OVERALL_flesh",nil,50],
			["TRYK_OVERALL_nok_flesh",nil,50],
			["TRYK_OVERALL_SAGE",nil,50],
			["TRYK_OVERALL_SAGE_BLKboots",nil,50],

			["TRYK_HRP_khk",nil,50],
			["TRYK_HRP_UCP",nil,50],
			["TRYK_HRP_USMC",nil,50],
			["TRYK_DMARPAT_T",nil,50],
			["TRYK_C_AOR2_T",nil,50],
			["TRYK_T_BLK_PAD",nil,50],
			["TRYK_T_CSAT_PAD",nil,50],
			["TRYK_T_OD_PAD",nil,50],
			["TRYK_T_PAD",nil,50],
			["TRYK_T_T2_PAD",nil,50],
			["TRYK_T_TAN_PAD",nil,50],
			["TRYK_T_camo_3c",nil,50],
			["TRYK_T_camo_3c_BG",nil,50],
			["TRYK_T_camo_Wood",nil,50],
			["TRYK_T_camo_Wood_BG",nil,50],
			["TRYK_T_camo_wood_marpat",nil,50],
			["TRYK_T_camo_wood_marpat_BG",nil,50],
			["TRYK_T_camo_Desert_marpat",nil,50],
			["TRYK_T_camo_desert_marpat_BG",nil,50],
			["TRYK_T_camo_tan",nil,50],
			["TRYK_B_USMC_R",nil,50],
			["TRYK_B_USMC_R_ROLL",nil,50],
			["TRYK_B_TRYK_MTP_T",nil,50],
			["TRYK_B_TRYK_OCP_T",nil,50],
			["TRYK_B_TRYK_OCP_D_T",nil,50],
			["TRYK_B_TRYK_UCP_T",nil,50],
			["TRYK_U_pad_hood_Blk",nil,50],
			["TRYK_U_pad_hood_Blod",nil,50],
			["TRYK_U_pad_hood_BKT2",nil,50],
			["TRYK_U_pad_hood_Cl",nil,50],
			["TRYK_U_pad_hood_Cl_blk",nil,50],
			["TRYK_U_pad_hood_CSATBlk",nil,50],
			["TRYK_U_pad_hood_odBK",nil,50],
			["TRYK_U_pad_hood_tan",nil,50],
			["TRYK_U_nohoodPcu_gry",nil,50],
			["TRYK_U_hood_mc",nil,50],
			["TRYK_U_hood_nc",nil,50],
			["TRYK_U_denim_hood_3c",nil,50],
			["TRYK_U_denim_hood_blk",nil,50],
			["TRYK_U_denim_hood_mc",nil,50],
			["TRYK_U_denim_hood_nc",nil,50],
			["TRYK_U_denim_jersey_blk",nil,50],
			["TRYK_U_denim_jersey_blu",nil,50],
			["TRYK_U_pad_j",nil,50],

			["TRYK_U_pad_j_blk",nil,50],
			["TRYK_U_taki_BL",nil,50],
			["TRYK_U_taki_G_BL",nil,50],
			["TRYK_U_taki_BLK",nil,50],
			["TRYK_U_taki_G_BLK",nil,50],
			["TRYK_U_taki_COY",nil,50],
			["TRYK_U_taki_G_COY",nil,50],
			["TRYK_U_taki_wh",nil,50],
			["TRYK_U_taki_G_WH",nil,50],
			["TRYK_U_Bts_PCUs",nil,50],
			["TRYK_U_Bts_PCUGs",nil,50],
			["TRYK_U_Bts_PCUODs",nil,50],
			["TRYK_U_Bts_GRYGRY_PCUs",nil,50],
			["TRYK_U_Bts_UCP_PCUs",nil,50],
			["TRYK_U_Bts_Wood_PCUs",nil,50],
			["TRYK_U_B_ACU",nil,50],
			["TRYK_U_B_ACUTshirt",nil,50],
			["TRYK_U_B_ARO1_CombatUniform",nil,50],
			["TRYK_U_B_ARO1R_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_BLK_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_BLK_R_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_CBR_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_CBR_R_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_GR_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_GR_R_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_GRY_CombatUniform",nil,50],
			["TRYK_U_B_ARO1_GRY_R_CombatUniform",nil,50],
			["TRYK_U_B_ARO2_CombatUniform",nil,50],
			["TRYK_U_B_ARO2R_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_BLK_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_BLK_R_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_GRY_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_GRY_R_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_OD_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_OD_R_CombatUniform",nil,50],
			["TRYK_U_B_BLOD_T",nil,50],
			["TRYK_U_B_BLTAN_T",nil,50],
			["TRYK_U_B_BLKTAN_CombatUniform",nil,50],
			["TRYK_U_B_BLKTANR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_BLKOCP_CombatUniform",nil,50],
			["TRYK_U_B_BLKOCP_R_CombatUniformTshirt",nil,50],
			["TRYK_U_B_C01_Tsirt",nil,50],
			["TRYK_U_B_C02_Tsirt",nil,50],
			["TRYK_U_B_3c",nil,50],
			["TRYK_U_B_3cr",nil,50],
			["TRYK_U_B_BLK3CD",nil,50],
			["TRYK_U_B_BLK3CD_Tshirt",nil,50],
			["TRYK_U_B_BLKTAN",nil,50],
			["TRYK_U_B_BLKTAN_Tshirt",nil,50],
			["TRYK_U_B_BLK_OD",nil,50],
			["TRYK_U_B_BLK_OD_Tshirt",nil,50],
			["TRYK_U_B_OD_BLK",nil,50],
			["TRYK_U_B_OD_BLK_2",nil,50],
			["TRYK_U_B_ODTAN_Tshirt",nil,50],
			["TRYK_U_B_Sage_T",nil,50],
			["TRYK_U_B_Sage_Tshirt",nil,50],
			["TRYK_U_B_BLK_TAN_1",nil,50],
			["TRYK_U_B_BLK_TAN_2",nil,50],
			["TRYK_U_B_3CD_Delta_BDU",nil,50],
			["TRYK_U_B_3CD_Delta_BDUTshirt",nil,50],
			["TRYK_U_B_3CD_Ranger_BDU",nil,50],
			["TRYK_U_B_3CD_Ranger_BDUTshirt",nil,50],
			["TRYK_U_B_3CD_BLK_BDUTshirt",nil,50],
			["TRYK_U_B_3CD_BLK_BDUTshirt2",nil,50],
			["TRYK_U_B_fleece",nil,50],
			["TRYK_U_B_fleece_UCP",nil,50],
			["TRYK_U_B_GRTAN_CombatUniform",nil,50],
			["TRYK_U_B_GRTANR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_GRYOCP_CombatUniform",nil,50],
			["TRYK_U_B_GRYOCP_R_CombatUniformTshirt",nil,50],
			["TRYK_U_B_MARPAT_Desert",nil,50],
			["TRYK_U_B_MARPAT_Desert_Tshirt",nil,50],
			["TRYK_U_B_MARPAT_Desert2",nil,50],
			["TRYK_U_B_MARPAT_Desert2_Tshirt",nil,50],
			["TRYK_U_B_MARPAT_Wood",nil,50],
			["TRYK_U_B_MARPAT_Wood_Tshirt",nil,50],
			["TRYK_U_B_MARPAT_WOOD_CombatUniform",nil,50],
			["TRYK_U_B_MARPAT_WOOD_CombatUniformTshirt",nil,50],
			["TRYK_U_B_MTP_CombatUniform",nil,50],
			["TRYK_U_B_MTP_R_CombatUniform",nil,50],
			["TRYK_U_B_MTP_BLK_CombatUniform",nil,50],
			["TRYK_U_B_MTP_BLK_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCPD_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCPD_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_BLK_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_c_BLK_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_BLK_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_OCP_BLK_c_R_CombatUniform",nil,50],
			["TRYK_U_B_OD_OD_CombatUniform",nil,50],
			["TRYK_U_B_OD_OD_R_CombatUniform",nil,50],
			["TRYK_U_B_ODTAN_CombatUniform",nil,50],
			["TRYK_U_B_ODTANR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_PCUs",nil,50],
			["TRYK_U_B_PCUs_R",nil,50],
			["TRYK_U_B_PCUGs",nil,50],
			["TRYK_U_B_PCUGs_BLK",nil,50],
			["TRYK_U_B_PCUGs_BLK_R",nil,50],
			["TRYK_U_B_PCUGs_gry",nil,50],
			["TRYK_U_B_PCUGs_gry_R",nil,50],
			["TRYK_U_B_PCUGHs",nil,50],
			["TRYK_U_B_PCUODHs",nil,50],
			["TRYK_U_B_GRY_PCUs",nil,50],
			["TRYK_U_B_GRY_PCUs_R",nil,50],
			["TRYK_U_B_UCP_PCUs",nil,50],
			["TRYK_U_B_UCP_PCUs_R",nil,50],
			["TRYK_U_B_Wood_PCUs",nil,50],
			["TRYK_U_B_Wood_PCUs_R",nil,50],
			["TRYK_U_B_PCUODs",nil,50],
			["TRYK_U_B_PCUGs_OD",nil,50],
			["TRYK_U_B_PCUGs_OD_R",nil,50],
			["TRYK_U_B_AOR1_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_AOR2_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_BLK_OD_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_BLK_tan_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_wh_blk_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_wh_OD_Rollup_CombatUniform",nil,50],
			["TRYK_U_B_wh_tan_Rollup_CombatUniform",nil,50],
			
			["TRYK_U_B_Snowt",nil,50],
			["TRYK_U_B_Snow_CombatUniform",nil,50],
			["TRYK_U_B_woodtan_CombatUniform",nil,50],
			["TRYK_U_B_woodtanR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_TANOCP_CombatUniform",nil,50],
			["TRYK_U_B_TANOCP_R_CombatUniformTshirt",nil,50],
			["TRYK_U_B_TANTAN_CombatUniform",nil,50],
			["TRYK_U_B_TANTAN_R_CombatUniform",nil,50],
			["TRYK_U_B_JSDF_CombatUniform",nil,50],
			["TRYK_U_B_JSDF_CombatUniformTshirt",nil,50],
			["TRYK_U_B_NATO_UCP_CombatUniform",nil,50],
			["TRYK_U_B_NATO_UCP_R_CombatUniform",nil,50],
			["TRYK_U_B_NATO_UCP_GRY_CombatUniform",nil,50],
			["TRYK_U_B_NATO_UCP_GRY_R_CombatUniform",nil,50],
			["TRYK_U_B_PCUHs",nil,50],
			["TRYK_U_B_PCUHsW",nil,50],
			["TRYK_U_B_PCUHsW2",nil,50],
			["TRYK_U_B_PCUHsW3",nil,50],
			["TRYK_U_B_PCUHsW3nh",nil,50],
			["TRYK_U_B_PCUHsW4",nil,50],
			["TRYK_U_B_PCUHsW5",nil,50],
			["TRYK_U_B_PCUHsW6",nil,50],
			["TRYK_U_B_Woodland",nil,50],
			["TRYK_U_B_Woodland_Tshirt",nil,50],
			["TRYK_U_B_wood_CombatUniform",nil,50],
			["TRYK_U_B_woodR_CombatUniformTshirt",nil,50],
			["TRYK_U_B_WDL_GRY_CombatUniform",nil,50],
			["TRYK_U_B_WDL_GRY_R_CombatUniform",nil,50],
			["TRYK_U_B_Wood_T",nil,50],
			["TRYK_U_B_wood3c_CombatUniform",nil,50],
			["TRYK_U_B_wood3c_CombatUniformTshirt",nil,50],
			["TRYK_U_B_WOOD_MARPAT_CombatUniform",nil,50],
			["TRYK_U_B_WOOD_MARPAT_CombatUniformTshirt",nil,50],
			
			["U_GhillieSuit_A",nil,150],
			["U_I_GhillieSuit",nil,150],
			["U_GhillieSuit_C",nil,150],
			["U_O_GhillieSuit",nil,150],
			["U_GhillieSuit_E",nil,150],
			["U_B_GhillieSuit",nil,150],
			["U_I_FullGhillie_ard","Vollst. Ghillie (Trocken)",200],
			["U_I_FullGhillie_sard","Wookie-Anzug (Halbtrocken)",200],
			["U_I_FullGhillie_lsh","Wookie-Anzug (Grün)",200],
			
		//Anzüge
			["KAEL_SUITS_BR_Judge",nil,250],
			["KAEL_SUITS_BLK_F",nil,250],
			["KAEL_SUITS_BR_F",nil,250],
			["KAEL_SUITS_BR_F3",nil,250],
			["KAEL_SUITS_BR_F4",nil,250],
			["KAEL_SUITS_BR_F5",nil,250],
			["KAEL_SUITS_BR_F6",nil,250],
			["KAEL_SUITS_BR_F7",nil,250],
			["KAEL_SUITS_BR_F8",nil,250],
			["KAEL_SUITS_BR_F9",nil,250],
			["KAEL_SUITS_BR_F10",nil,250],
			["KAEL_SUITS_BR_F11",nil,250],
			["KAEL_SUITS_BR_F12",nil,250],
			["KAEL_SUITS_BR_F13",nil,250],
			["KAEL_SUITS_BR_F14",nil,250],
			["KAEL_SUITS_BR_F15",nil,250],
			["KAEL_SUITS_BR_F16",nil,250],
			["KAEL_SUITS_BR_F17",nil,250],
			["KAEL_SUITS_BR_F18",nil,250],
			["KAEL_SUITS_BR_F19",nil,250],
			["KAEL_SUITS_BR_F20",nil,250],
			["KAEL_SUITS_BR_F21",nil,250],
			["KAEL_SUITS_BR_F22",nil,250],
			["KAEL_SUITS_BR_F23",nil,250],
			["KAEL_SUITS_BR_F24",nil,250],
			["KAEL_SUITS_BR_F25",nil,250],
			["KAEL_SUITS_BR_F26",nil,250],
			["KAEL_SUITS_BR_F27",nil,250],
			["KAEL_SUITS_BR_F28",nil,250],
			["KAEL_SUITS_BR_F29",nil,250],
			["KAEL_SUITS_BR_F30",nil,250],
			["KAEL_SUITS_BR_F31",nil,250],
			["KAEL_SUITS_BR_F32",nil,250],
			["KAEL_SUITS_BR_F33",nil,250],
			["KAEL_SUITS_BR_F34",nil,250],
			["KAEL_SUITS_BR_F35",nil,250],
			["U_CivilianSuit_A",nil,250],
			["U_CivilianSuit_C",nil,250],
			["U_CivilianSuit_B",nil,250],
			["TRYK_SUITS_BLK_F",nil,250],
			["TRYK_SUITS_BR_F",nil,250],
			["U_CivilianCoat_D",nil,250],
			["U_CivilianCoat_E",nil,250],
			["U_CivilianCoat_F",nil,250],
			["U_CivilianCoat_B",nil,250],
			["U_CivilianCoat_C",nil,250],
			["U_MilitaryCoat_A",nil,250],
			["U_MilitaryCoat_B",nil,250],
			["U_MilitaryCoat_C",nil,250],
			["U_MilitaryCoat_D",nil,250]
		];
	};
	
	//Hats
	case 1:
	{
		[
		//Fbi
			["do_fbicap","FBI Mütze",1],
			["H_HelmetB_black","FBI Helm",5],
			["TRYK_H_PASGT_OD","Einsatzhelm (Grün)",10],
			["H_Watchcap_blk","Wollmütze Headset (Schwarz)",5],
			["TRYK_H_woolhat","Wollmütze (Schwarz)",5],
			["H_Watchcap_camo","Wollmütze Headset (grün)",5],
			
		//Zivil
			["TRYK_Kio_Balaclava",nil,10],
		
			["TRYK_R_CAP_BLK ","Backcappy Schwarz",10],
			["TRYK_H_Bandana_wig","Perücken Bandana",10],
			
			["TRYK_ESS_CAP",nil,10],
			["TRYK_ESS_CAP_tan",nil,10],
			["TRYK_H_headsetcap_Glasses",nil,10],
			["TRYK_H_headsetcap_blk_Glasses",nil,10],
			["TRYK_r_cap_blk_Glasses",nil,10],
			["TRYK_R_CAP_TAN",nil,10],
			["TRYK_r_cap_tan_Glasses",nil,10],
			["TRYK_H_TACEARMUFF_H",nil,10],
		
			["TRYK_H_woolhat",nil,10],
			["TRYK_H_woolhat_WH",nil,10],
			["TRYK_H_woolhat_cu",nil,10],
			["TRYK_H_woolhat_CW",nil,10],
		
			["H_Watchcap_cbr",nil,10],
			["H_Watchcap_camo",nil,10],
			["H_Watchcap_blk",nil,10],
			["H_Watchcap_khk",nil,10],
			
			["H_Booniehat_DMARPAT",nil,10],
			["H_Booniehat_rgr",nil,10],
			["H_Booniehat_GCAMO",nil,10],
		
			["H_Hat_Pagri",nil,10],
			["H_Hat_Pagri_B",nil,10],
			["H_Hat_Pagri_C",nil,10],
			
			["H_Hat_HelmetCrewR",nil,10],
			["H_Hat_Pakol",nil,10],
			
			["H_Hat_Beret_Basque_A",nil,10],
			["H_Hat_Beret_Basque_B",nil,10],
			["H_Hat_Beret_Basque_C",nil,10],
			["H_Hat_Beret_Basque_D",nil,10],
		
			["H_Hat_HelmetT","Kriegshelm",10],
			["H_Hat_HelmetA","Kriegshelm Grün",10],
			["H_Hat_HelmetC","Kriegshelm Tarnfleck",10],
			["H_Hat_HelmetConical","Asia Hut",10],
			["H_Hat_Boonie_Cowboy","Cowboy Hut",10],
			["H_Hat_CapSov_A","Sovjet Braun",10],
			["H_Hat_CapSov_B","Sovjet Schwarz",10],
			["H_Hat_CapSov_C","Sovjet Grün",10],
			
			["TRYK_H_Booniehat_JSDF","Army Hut",10],
			["TRYK_H_wig","Perücke",10],
			["TRYK_H_Bandana_H",nil,10],
			["TRYK_H_Bandana_wig_g",nil,10],
			
			["H_Hat_Ushanka",nil,10],
			["H_Hat_Ushanka_Rnd_A",nil,10],
			["H_Hat_Ushanka_Rnd_B",nil,10],
			["H_Hat_Ushanka_Rnd_C",nil,10],
			["H_Hat_Ushanka_Rnd_D",nil,10],
			
			["H_Hat_Turban_A",nil,10],
			["H_Hat_Turban_B",nil,10],
			["H_Hat_Turban_C",nil,10],
			["H_Hat_Turban_D",nil,10],
			["H_Hat_Turban_E",nil,10],
			
			["H_Hat_Taqiyah_A",nil,10],
			["H_Hat_Taqiyah_B",nil,10],
			["H_Hat_Taqiyah_C",nil,10],
			["H_Hat_Taqiyah_D",nil,10],
			["H_Hat_Taqiyah_E",nil,10],
			
			["H_Bandanna_blu",nil,10],
			["H_Bandanna_gry",nil,10],
			["H_Bandanna_surfer_grn",nil,10],
			["H_Bandanna_surfer_blk",nil,10],
			["H_Bandanna_camo",nil,10],
			["H_Hat_Boonie_Flecktarn",nil,10],
			["H_Hat_Boonie_Green",nil,10],
			["H_Hat_Boonie_Marpat",nil,10],
			["H_Hat_Boonie_Tiger",nil,10],
			["H_Hat_Boonie_Woodland",nil,10],
			["H_Booniehat_khk_hs",nil,10],
			["H_Booniehat_mcamo",nil,10],
			["H_Booniehat_oli",nil,10],
			["H_Booniehat_dgtl",nil,10],
			["H_Hat_Boonie_Cowboy",nil,10],
			["ALE_H_Cowboy_Black",nil,10],
			["ALE_H_Cowboy_White",nil,10],
			["H_Hat_Golf",nil,10],
			["H_Hat_Golf_Black",nil,10],
			["H_Hat_Golf_Blue",nil,10],

			["TRYK_H_headset2",nil,10],
			["H_ALFR_Headset",nil,10],
			["H_Hat_camo",nil,10],
			["A3L_longhairblack",nil,10],
			["A3L_longhairblond",nil,10],
			["A3L_longhairbrown",nil,10],
			["H_Cap_surfer",nil,10],
			["H_MilCap_blue",nil,10],
			["H_MilCap_gry",nil,10],
			["H_MilCap_dgtl",nil,10],
			["H_MilCap_mcamo",nil,10],
			["H_MilCap_ocamo",nil,10],
			["ALE_H_NewEra_Black",nil,10],
			["ALE_H_NewEra_Cyan",nil,10],
			["ALE_H_NewEra_Superman",nil,10],
			["ALE_H_NewEra_Monster",nil,10],
			["ALE_H_NewEra_Lakers",nil,10],
			["ALE_H_NewEra_Redsox",nil,10],
			["ALE_H_Cowboy_Brown",nil,10],
			["ALE_H_Cowboy_Black",nil,10],
			["ALE_H_Cowboy_White",nil,10],
			["ALE_H_NewEra_Rouge",nil,10],
			
			["H_ALFR_Dallas_Mask",nil,25],
			["H_ALFR_Samurai_Mask",nil,25],
			["H_ALFR_Sheep_Mask",nil,25],
			["H_ALFR_Headset",nil,25],
			["H_ALFR_HorseMask",nil,25],
			["H_ALFR_DinoMask",nil,25],
			["cg_dinomask",nil,25],
			["cg_dinomask_p",nil,25],
			["cg_dinomask_r",nil,25],
			["H_ALFR_HorseMask_pnk",nil,25],
			["cg_horsehead",nil,25],
			["cg_horsehead_2",nil,25],
			["cg_horsehead_blk",nil,25],
			["cg_horsehead_pnk",nil,25],
			
			["H_ALFR_Heist_Mask_1",nil,25],
			["H_ALFR_Heist_Mask_2",nil,25],
			["H_ALFR_Heist_Mask_3",nil,25],
			["H_ALFR_Heist_Mask_4",nil,25],
			["H_ALFR_Heist_Mask_5",nil,25],
			["H_ALFR_Heist_Mask_6",nil,25],
			["H_ALFR_Heist_Mask_7",nil,25],
			
			["Kio_Hat",nil,25],
			["Kio_Capital_Hat",nil,25],
			["Kio_Spinning_Hat",nil,25],
			["Kio_Santa_Hat",nil,25],
			["kio_no1_hat",nil,25],
			["kio_pirate_hat",nil,25],
			["Kio_Afro_Hat",nil,25],			
			["kio_vfv_mask",nil,25],
			
			["H_ALFR_OVERKILL_I",nil,25],
			["H_ALFR_OVERKILL_II",nil,25],
			["H_ALFR_OVERKILL_III",nil,25],
			["H_ALFR_OVERKILL_IV",nil,25],
			
			["Masque_Santa","Scarry Santa",25],
			["Masque_archNemesis","Monster Maske",25],
			["Masque_Smiley","Scarry Clown",25],
			["Masque_Religieuse","Nonnen Maske",25],
			["Masque_Macrilleuse","Scarry Clown (Klein)",25],
			["Masque_Unic","Einhorn Maske",25],
			
			["Gorb_Gingerbread1",nil,50],
			["Gorb_AngryGingerbread3",nil,50],
			["Gorb_PuddingHat",nil,50],
			["Gorb_PuddingMask1",nil,50],
			["Gorb_PuddingMask2",nil,50],
			["Gorb_CoolElfMask1",nil,50],
			["Gorb_CoolElfMask2",nil,50],
			["Gorb_CoolElfMask3",nil,50],
			["Gorb_Elf",nil,50],
			["Gorb_ElfMask1",nil,50],
			["Gorb_ElfMask2",nil,50],
			["Gorb_ElfMask3",nil,50],
			["Gorb_FestiveHat1",nil,50],
			["Gorb_FestiveHat2",nil,50],
			["Gorb_FestiveHat3",nil,50],
			["Gorb_FestiveHat4",nil,50],
			["Gorb_FestiveHat5",nil,50],
			["Gorb_FestiveHat6",nil,50],
			["Gorb_FestiveHat7",nil,50],
			["Gorb_FestiveHat8",nil,50],
			["Gorb_PlaidHat1",nil,50],
			["Gorb_PlaidHat2",nil,50],
			["Gorb_PlaidHat3",nil,50],
			["Gorb_PlaidHat4",nil,50],
			["Gorb_KnittedHat1",nil,50],
			["Gorb_KnittedHat2",nil,50],
			["Gorb_KnittedHat3",nil,50],
			["Gorb_KnittedHat4",nil,50],
			["Gorb_MrsClaus1",nil,50],
			["Gorb_MrsClaus2",nil,50],
			["Gorb_MrsClaus3",nil,50],
			["Gorb_Penguin",nil,50],
			["Gorb_Reindeer",nil,50],
			["Gorb_RoughSantaClaus1",nil,50],
			["Gorb_RoughSantaClaus2",nil,50],
			["Gorb_RoughSantaClaus3",nil,50],
			["Gorb_SantaHat",nil,50],
			["Gorb_SantaHat_Green",nil,50],
			["Gorb_Santa_White",nil,50],
			["Gorb_Santa_Tan",nil,50],
			["Gorb_Santa_Black",nil,50],
			["Gorb_Snowman",nil,50],
			["Gorb_TreeMask1",nil,50],
			["Gorb_TreeMask2",nil,50],
			["Gorb_TreeMask3",nil,50],
			["Gorb_TreeMask4",nil,50],
			["Gorb_TreeMask5",nil,50],
			["Gorb_TreeMask6",nil,50],
			["Gorb_TurkeyMask1",nil,50],
			["Gorb_TurkeyMask2",nil,50],
			["Gorb_TurkeyMask3",nil,50],
			["Gorb_UglyMrsClaus1",nil,50],
			["Gorb_UglyMrsClaus2",nil,50],
			["Gorb_UglyMrsClaus3",nil,50],
			
			["Masque_Alien1",nil,50],
			["Masque_Anonymous",nil,50],
			["Masque_archNemesis",nil,50],
			["Masque_Arnold",nil,50],
			["Masque_Aubrey",nil,50],
			["Masque_Bonnie",nil,50],
			["Masque_Bush",nil,50],
			["Masque_Chains",nil,50],
			["Masque_Chuck",nil,50],
			["Masque_Clinton",nil,50],
			["Masque_Clover",nil,50],
			["Masque_Dallas",nil,50],
			["Masque_Fish",nil,50],
			["Masque_forceAlpha",nil,50],
			["Masque_Gombo",nil,50],
			["Masque_GdG",nil,50],
			["Masque_Hockey",nil,50],
			["Masque_Hoxton",nil,50],
			["Masque_Incendiaire",nil,50],
			["Masque_Lincoln",nil,50],
			["Masque_Lion",nil,50],
			["Masque_Macrilleuse",nil,50],
			["Masque_Mark",nil,50],
			["Masque_Metalhead",nil,50],
			["Masque_Momie",nil,50],
			["Masque_Optimiste",nil,50],
			["Masque_Orc",nil,50],
			["Masque_Religieuse",nil,50],
			["Masque_Santa",nil,50],
			["Masque_Smiley",nil,50],
			["Masque_Mempo",nil,50],
			["Masque_speedRunner",nil,50],
			["Masque_Unic",nil,50],
			["Masque_Wolfv2",nil,50],
			["Masque_zeus",nil,50],
			
			["H_GingerbreadMask",nil,50],
			["H_UltronMask",nil,50],
			["H_KermitMask",nil,50],
			["H_JasonMask",nil,50],
			["H_RAAMMask",nil,50],
			["H_HulkMask",nil,50],
			["H_GrantMask",nil,50],
			["H_AntmanMask",nil,50],
			["H_AugustusMask",nil,50],
			["H_GuyFawkesMask",nil,50],
			["H_BatmanMask",nil,50],
			["H_DeadpoolMask",nil,50],
			["H_FranklinMask",nil,50],
			["H_LincolnMask",nil,50],
			["H_MickeyMask",nil,50],
			["H_NixonMask",nil,50],
			["H_ObamaMask",nil,50],
			["H_PatriotMask",nil,50],
			["H_ShrekMask",nil,50],
			["H_ScarecrowMask",nil,50],
			["H_SpidermanMask",nil,50],
			["H_SpongebobMask",nil,50],
			["H_SquidwardMask",nil,50],
			["H_StarFoxMask",nil,50],
			["H_WashingtonMask",nil,50],
			["H_VenomMask",nil,50],
			
			["A3L_Legoman","Legokopf",50],
			["A3L_Halloween_Pumpkinhead","Pumpkin",50],
			["A3L_Halloween_PredatorMask","Predator",50],		
			["A3L_Halloween_JigSaw","Jigsaw",50],
			["A3L_soa_helmet","Biker Helm",50],	
			["A3L_gangster_hat","Gangster Maske",50],
			["A3L_Mask","Maske",50],				
			["A3L_Crown","Krone",50],
			["A3L_Sombrero","Sombrero",50],
			["A3L_SkateHelmet_green",nil,50],
			["A3L_mexicanhat","Mexican Hut",50],
			["A3L_russianhat",nil,50],
			["jokermask",nil,50],
			["cowboyhat",nil,50],
			
		//Rebell
			["H_Hat_Face_Wrap",nil,25],
			["H_Hat_Face_Wrap_Desert",nil,25],
			["H_Hat_Face_Wrap_Olive",nil,25],
			["H_Hat_Face_Wrap_Red",nil,25],
			
			["H_Hat_Face_Wrap_Dark","Shemag G. Schwarz",25],
			["H_Hat_Face_Wrap_DPM","Shemag G. Tarn",25],
			
			["H_Hat_Kufiya_B",nil,25],
			["H_Hat_Kufiya_F",nil,25],
			["H_Hat_Kufiya_D",nil,25],
			["H_Hat_Kufiya_C",nil,25],
			["H_Hat_Kufiya",nil,25],
			["H_Hat_Kufiya_G",nil,25],
			["H_Hat_Kufiya_R",nil,25],
			
			["H_ShemagOpen_tan",nil,25],
			["H_Shemag_olive",nil,25],
			["H_ShemagOpen_khk",nil,25],
			
			["H_HelmetO_ocamo",nil,25],
			["H_MilCap_oucamo",nil,25],
			["H_Bandanna_camo",nil,25],
			
			["H_Hat_Face_Balaclava_T",nil,25],
			["H_Hat_Face_Wrap_Black",nil,25],
			["H_Hat_Face_Wrap_Gold",nil,25],
	
			["H_Hat_Face_Wrap_Dark",nil,25],
			["H_Hat_Face_Wrap_White",nil,25],
			["H_Hat_Face_Wrap_DPM",nil,25],
			["H_Hat_Face_Wrap_Flecktarn",nil,25],
			["H_Hat_Face_Wrap_Sand",nil,25],
			
			["H_ALFR_Metal_Facemask_gry",nil,25],
			["H_ALFR_Metal_Facemask_oli",nil,25],
			["H_ALFR_Metal_Facemask_sand",nil,25],
			["H_ALFR_Metal_Facemask_blk",nil,25],
			
			["H_ALFR_Metal_Gasmask_RU_fuckyou",nil,25],
			["H_ALFR_Metal_Gasmask_RU_grey",nil,25],
			["H_ALFR_Metal_Gasmask_RU_khk",nil,25],
			["H_ALFR_Metal_Gasmask_RU_oli",nil,25],
			["H_ALFR_Metal_Gasmask_RU_blk",nil,25],
			["H_ALFR_Gasmask",nil,25],
			
			["H_Hat_Face_Cover_Black",nil,25],
			["H_Hat_Face_Cover_Gold",nil,25],
			["H_Hat_Face_Cover_Green",nil,25],
			
			["kio_skl_msk_weed",nil,25],
			["kio_skl_msk_UK",nil,25],
			["kio_skl_msk_US",nil,25],
			["kio_skl_msk_scot",nil,25],
			["kio_skl_msk_redranger",nil,25],
			["kio_skl_msk_p",nil,25],
			["kio_skl_msk_pun",nil,25],
			["kio_skl_msk_o",nil,25],
			["kio_skl_msk_nirish",nil,25],
			["kio_skl_msk_irish",nil,25],
			["kio_skl_msk_grey",nil,25],
			["kio_skl_msk_german",nil,25],
			["kio_skl_msk_GOW",nil,25],
			["kio_skl_msk_frost",nil,25],
			["kio_skl_msk_fran",nil,25],
			["kio_skl_msk_fire",nil,25],
			["kio_skl_msk_black",nil,25],
			["kio_skl_msk_blood",nil,25],
			["kio_skl_msk_can",nil,25],
			["kio_skl_msk",nil,25],
			["kio_skl_msk_red",nil,25],
			["kio_skl_msk_grn",nil,25]
			
		];
	};
	
	//Glasses
	case 2:
	{
		[
			["TRYK_US_ESS_Glasses_BLK","Einsatzbrille",5],
			["G_Aviator",nil,5],
			["G_Lady_Blue",nil,5],
			["G_Spectacles_Tinted",nil,5],
			["G_Squares",nil,5],
			["G_Sport_Red",nil,5],
			["G_Sport_Blackyellow",nil,5],
			["G_Sport_BlackWhite",nil,5],
			["G_Sport_Checkered",nil,5],
			["G_Sport_Blackred",nil,5],
			["G_Sport_Greenblack",nil,5],
			["G_Tactical_Clear",nil,5],
			["G_Tactical_Black",nil,5],
			["G_Lady_Mirror",nil,5],
			["G_Lady_Dark",nil,5],
			["G_Lady_Blue",nil,5],
			
			["L_Shemagh_Gry",nil,5],
			["L_Shemagh_OD",nil,5],
			["L_Shemagh_Red",nil,5],
			["L_shemagh_white",nil,5],
			
			["NeckTight_Dmaripat",nil,5],
			["NeckTight_Gry",nil,5],
			["NeckTight_OD",nil,5],
			["NeckTight_Red",nil,5],
			["NeckTight_Tan",nil,5],
			["NeckTight",nil,5],
			
			["H_ALFR_SkiMask_Glasses_6",nil,5],
			["H_ALFR_SkiMask_Glasses_5",nil,5],
			["H_ALFR_SkiMask_Glasses_4",nil,5],
			["H_ALFR_SkiMask_Glasses_7",nil,5],
			["H_ALFR_SkiMask_Glasses_8",nil,5],
			["H_ALFR_SkiMask_Glasses_3",nil,5],
			["H_ALFR_SkiMask_Glasses_1",nil,5],
			["H_ALFR_SkiMask_Glasses_2",nil,5],
			
			["Masque_Solitaire",nil,5],
			["Masque_Chirurgical",nil,5],
			["A3L_FatHead",nil,5],
			
			["SFG_Tac_smallBeardD",nil,5],
			["SFG_Tac_BeardD","Bart (Dunkel)",5],
			["SFG_Tac_ChopsD","Mutton Chops (Dunkel)",5],
			["SFG_Tac_moustacheD","Moustache (Dunkel)",5],
			["SFG_Tac_chinlessbD","Chinless Beard (Dunkel)",5],
			
			["SFG_Tac_smallBeardG",nil,5],
			["SFG_Tac_BeardG","Bart (Ginger)",5],
			["SFG_Tac_ChopsG","Mutton Chops (Ginger)",5],
			["SFG_Tac_moustacheG","Moustache (Ginger)",5],
			["SFG_Tac_chinlessbG","Chinless Beard (Ginger)",5],
			
			["SFG_Tac_smallBeardO",nil,5],
			["SFG_Tac_BeardO","Bart (Alt)",5],
			["SFG_Tac_ChopsO","Mutton Chops (Alt)",5],
			["SFG_Tac_moustacheO","Moustache (Alt)",5],
			["SFG_Tac_chinlessbO","Chinless Beard (Alt)",5],
			
			["SFG_Tac_smallBeardB",nil,5],
			["SFG_Tac_BeardB","Bart (Blond)",5],
			["SFG_Tac_ChopsB","Mutton Chops (Blond)",5],
			["SFG_Tac_moustacheB","Moustache (Blond)",5],
			["SFG_Tac_chinlessbB","Chinless Beard (Blond)",5],
			
			["TRYK_Beard_BW","Vollbart",5],
			["TRYK_Beard_BW2",nil,5],
			["TRYK_Beard_BW3",nil,5],
			["TRYK_Beard_BW4",nil,5],

			["TRYK_Beard","Vollbart",5],
			["TRYK_Beard2",nil,5],
			["TRYK_Beard3","Vollbart",5],
			["TRYK_Beard4",nil,5],
			
			["TRYK_Beard_Gr",nil,5],
			["TRYK_Beard_Gr2",nil,5],
			["TRYK_Beard_Gr3","Vollbart",5],
			["TRYK_Beard_Gr4",nil,5],
			
			["TRYK_Beard_BK",nil,5],
			["TRYK_Beard_BK2","Vollbart",5],
			["TRYK_Beard_BK3","Vollbart",5],
			["TRYK_Beard_BK4","Vollbart",5],
	
			["TRYK_headset_Glasses",nil,5],
			
		//Rebell
			["A3L_Balaclava",nil,15],
			["Balaclava_Black",nil,15],
			["Balaclava_GRY",nil,15],
			["Balaclava_OD",nil,15],
			["T_HoodACUCLR",nil,15],
			["T_HoodBDUCLR",nil,15],
			["T_HoodBlkCLR",nil,15],
			["T_HoodMDCLR",nil,15],
			["T_HoodODCLR",nil,15],
			["T_HoodTanCLR",nil,15],
			["T_HoodMWCLR",nil,15],
			
			["Shemagh_FaceGry",nil,15],
			["Shemagh_FaceOD",nil,15],
			["Shemagh_FaceRed",nil,15],
			["Shemagh_FaceTan",nil,15],
			["Shemagh_Face",nil,15],
			
			["G_Balaclava_blk",nil,15],
			
			["PU_shemagh_GryO",nil,15],
			["PU_shemagh_ODO",nil,15],
			["PU_shemagh_TanO",nil,15],
			["PU_shemagh_WhiteO",nil,15],
			
			["SAS_shemagh_OD",nil,15],
			["SAS_shemagh_Tan",nil,15],
			["SAS_shemagh_White",nil,15],
			
			["Mask_M40",nil,15],
			["Mask_M40_OD",nil,15],
			["Mask_M50",nil,15]
		];
	};
	
	//Vest
	case 3:
	{
		[
		//Fbi
			//["A3L_policevest1","FBI Weste",100],
			["TRYK_V_Bulletproof_BLK","FBI Weste",100],
			["TRYK_V_tacv1_FBI_BK","Einsatzweste (Grün)",200],
			
		//Zivil
			["V_BandollierB_cbr",nil,100],
			["V_BandollierB_khk",nil,100],
			["V_BandollierB_oli",nil,100],
			["V_BandollierB_blk",nil,100],
			["V_Rangemaster_belt",nil,100],
			["A3L_SpiderVest",nil,100],
			["A3L_SpookyVest",nil,100],
			
		//Rebell
			["V_PlateCarrierInd_PMC_blk",nil,300],
			["V_PlateCarrierInd_PMC_grn",nil,300],
			["V_PlateCarrierIA1_dgtl",nil,150],
			["V_PlateCarrierIA2_dgtl",nil,300],
			["V_PlateCarrier_light_digiCamo",nil,150],
			["V_PlateCarrier_heavy_digiCamo",nil,300],
			["TRYK_V_PlateCarrier_coyo_L",nil,150],
			["TRYK_V_PlateCarrier_coyo",nil,300],
			["TRYK_V_PlateCarrier_ACU_L",nil,150],
			["TRYK_V_PlateCarrier_ACU",nil,300],
			["TRYK_V_PlateCarrier_wood_L",nil,150],
			["TRYK_V_PlateCarrier_wood",nil,300],
			["TRYK_V_PlateCarrier_JSDF",nil,300],
			["Jamie_Rebell","Fuck U Police",300],

			["V_TacVest_darkblck",nil,150],
			
			["k_cut_1","Sinister Sons",150],
			["k_cut_2","Gold Gunners",150],
			["k_cut_3","Sons of Anarchy Mitglied",150],
			["k_cut_4","Sons of Anarchy Chef",150],
			["k_cut_5","Sons of Outlaws",150],
			
			["V_TacVest_TK",nil,150],
			["V_TacVest_brn",nil,150],
			["V_TacVest_khk",nil,150],
			["V_TacVest_oli",nil,150],
			["V_TacVest_blk",nil,150],
			["V_I_G_resistanceLeader_F",nil,150],
			["V_TacVest_camo",nil,150],
			
			["V_PlateCarrier_heavy_A",nil,150],
			["V_PlateCarrier_heavy_B",nil,150],
			["V_PlateCarrier_heavy_C",nil,150],
			["V_PlateCarrier_heavy_D",nil,150],
			["V_PlateCarrier_heavy_E",nil,150],
			["V_PlateCarrier_heavy_F",nil,150],
			
			["V_FlakJacket_Black",nil,150],
			["V_FlakJacket_KP_Black",nil,150],
			["V_FlakJacket_digiCamo",nil,150],
			["V_FlakJacket_KP_digiCamo",nil,150],
			["V_FlakJacket_Green",nil,150],
			["V_FlakJacket_KP_Green",nil,150],
			["V_FlakJacket_Tan",nil,150],
			["V_FlakJacket_KP_Tan",nil,150],
			["V_FlakJacket_Woodland",nil,150],
			["V_FlakJacket_KP_Woodland",nil,150],
			
			["TRYK_V_tacSVD_BK",nil,150],
			["TRYK_V_tacSVD_OD",nil,150],
			["TRYK_V_tacv1LC_BK",nil,150],
			["TRYK_V_tacv1LC_CY",nil,150],
			["TRYK_V_tacv1LC_OD",nil,150],
			
			["TRYK_V_ArmorVest_Winter",nil,150]
		];
	};

	//Backpacks
	case 4:
	{
		[
			["domepokemon",nil,75],
			["domepony",nil,75],
			["domegraffiti",nil,75],
			["domebuhse",nil,75],
			["domekappa_s",nil,75],
			["domekappa_blau",nil,75],
			["domekappa_p",nil,75],
			["domekappa_t",nil,75],
			["domekappa_w",nil,75],
			["domeadi_s",nil,75],
			["domeadi_blau",nil,75],
			["domeadi_p",nil,75],
			["domeadi_t",nil,75],
			["domeadi_w",nil,75],
			["domenik_s",nil,75],
			["domenik_blau",nil,75],
			["domenik_p",nil,75],
			["domenik_t",nil,75],
			["domenik_w",nil,75],
			["domepu_s",nil,75],
			["domepu_blau",nil,75],
			["domepu_p",nil,75],
			["domepu_t",nil,75],
			["domepu_w",nil,75],
			["TRYK_B_Carryall_wood",nil,100],
			["TRYK_B_Carryall_wh",nil,100],
			["TRYK_B_Carryall_blk",nil,100],
			["TRYK_B_Carryall_JSDF",nil,100],
			["TRYK_B_Alicepack",nil,100],
			["B_Carryall_oucamo",nil,100],
			["B_Carryall_cbr",nil,100],
			["B_Carryall_ocamo",nil,100],
			["B_Carryall_mcamo",nil,100],
			["B_Carryall_oli",nil,100],
			["B_Carryall_khk",nil,100],
			["TRYK_B_tube_blk",nil,50],
			["TRYK_B_tube_cyt",nil,50],
			["TRYK_B_tube_od",nil,50]
		];
	};
	
};
