/*
	File: fn_clothing_bruce.sqf
	Author: Bryan "Tonic" Boardwine

	Description:
	Master configuration file for Bruce's Outback Outfits.
*/
private["_filter"];
_filter = [_this,0,0,[0]] call BIS_fnc_param;
//Classname, Custom Display name (use nil for Cfg->DisplayName, price

//Shop Title Name
ctrlSetText[3103,"IKI Kleidungsladen"];

switch (_filter) do
{
	//Uniforms
	case 0:
	{
		[
			["A3L_Bikini_Girl",nil,175],
			["U_BasicBodyICE123",nil,150],

			["A3L_Character_Uniform","Freizeitkleidung",100],
			["A3L_Dude_Outfit","Kollegah Outfit",100],
			["A3L_Farmer_Outfit","Bauernkleidung",75],
			["A3L_Priest_Uniform","Priester",75],
			["taxi_uni","Taxi Uniform",25],
			["A3L_Worker_Outfit","Arbeiterkleidung",50],
			["HI1",nil,25],
			["RastaCiv",nil,25],
			["vacationshirt_uni",nil,25],

			["TRYK_shirts_DENIM_BK",nil,25],
			["TRYK_shirts_DENIM_BK_Sleeve",nil,25],
			["TRYK_shirts_DENIM_BL",nil,25],
			["TRYK_shirts_DENIM_BL_Sleeve",nil,25],
			["TRYK_shirts_DENIM_BWH",nil,25],
			["TRYK_shirts_DENIM_BWH_Sleeve",nil,25],
			["TRYK_shirts_DENIM_R",nil,25],
			["TRYK_shirts_DENIM_R_Sleeve",nil,25],
			["TRYK_shirts_DENIM_RED2",nil,25],
			["TRYK_shirts_DENIM_RED2_Sleeve",nil,25],
			["TRYK_shirts_DENIM_WH",nil,25],
			["TRYK_shirts_DENIM_WH_Sleeve",nil,25],
			["TRYK_shirts_DENIM_WHB",nil,25],
			["TRYK_shirts_DENIM_WHB_Sleeve",nil,25],
			["TRYK_shirts_DENIM_ylb",nil,25],
			["TRYK_shirts_DENIM_ylb_Sleeve",nil,25],
			["TRYK_shirts_DENIM_od",nil,25],
			["TRYK_shirts_DENIM_od_Sleeve",nil,25],
			["TRYK_shirts_OD_PAD",nil,25],
			["TRYK_shirts_OD_PAD_BK",nil,25],
			["TRYK_shirts_OD_PAD_BL",nil,25],
			["TRYK_shirts_OD_PAD_BLW",nil,25],
			["TRYK_shirts_OD_PAD_BLU3",nil,25],
			["TRYK_shirts_OD_PAD_RED2",nil,25],
			["TRYK_shirts_OD_PAD_YEL",nil,25],
			["TRYK_shirts_BLK_PAD",nil,25],
			["TRYK_shirts_BLK_PAD_BK",nil,25],
			["TRYK_shirts_BLK_PAD_BL",nil,25],
			["TRYK_shirts_BLK_PAD_BLW",nil,25],
			["TRYK_shirts_BLK_PAD_BLU3",nil,25],
			["TRYK_shirts_BLK_PAD_RED2",nil,25],
			["TRYK_shirts_BLK_PAD_YEL",nil,25],
			["TRYK_shirts_PAD",nil,25],
			["TRYK_shirts_PAD_BK",nil,25],
			["TRYK_shirts_PAD_BL",nil,25],
			["TRYK_shirts_PAD_BLW",nil,25],
			["TRYK_shirts_PAD_RED2",nil,25],
			["TRYK_shirts_PAD_BLU3",nil,25],
			["TRYK_shirts_PAD_YEL",nil,25],
			["TRYK_shirts_TAN_PAD",nil,25],
			["TRYK_shirts_TAN_PAD_BK",nil,25],
			["TRYK_shirts_TAN_PAD_BL",nil,25],
			["TRYK_shirts_TAN_PAD_BLW",nil,25],
			["TRYK_shirts_TAN_PAD_BLU3",nil,25],
			["TRYK_shirts_TAN_PAD_RED2",nil,25],
			["TRYK_shirts_TAN_PAD_YEL",nil,25],

			["TRYK_U_B_RED_T_BR",nil,25],
			["TRYK_U_B_RED_T_BG_BR",nil,25],
			["TRYK_U_B_BLK_T_BK",nil,25],
			["TRYK_U_B_BLK_T_BG_BK",nil,25],
			["TRYK_U_B_BLK_T_WH",nil,25],
			["TRYK_U_B_BLK_T_BG_WH",nil,25],
			["TRYK_U_B_Denim_T_BK",nil,25],
			["TRYK_U_B_Denim_T_BG_BK",nil,25],
			["TRYK_U_B_Denim_T_WH",nil,25],
			["TRYK_U_B_Denim_T_BG_WH",nil,25],

			["U_Rangemaster_A",nil,25],
			["U_Rangemaster_B",nil,25],
			["U_Rangemaster_C",nil,25],
			["U_Rangemaster_D",nil,25],
			["U_Rangemaster_E",nil,25],
			["U_Rangemaster_F",nil,25],
			["U_Rangemaster_G",nil,25],

			["U_CivilianTShirt_A",nil,25],
			["U_CivilianTShirt_B",nil,25],
			["U_CivilianTShirt_C",nil,25],
			["U_CivilianTShirt_D",nil,25],
			["U_CivilianTShirt_E",nil,25],
			["U_CivilianTShirt_F",nil,25],
			["U_CivilianTShirt_G",nil,25],

			["cg_awesome1",nil,25],
			["cg_bb1",nil,25],
			["cg_beats1",nil,25],
			["cg_burgerking1",nil,25],
			["cg_catvideos1",nil,25],
			["cg_condoms1",nil,25],
			["cg_csgo1",nil,25],
			["cg_dad1",nil,25],
			["cg_deeznuts1",nil,25],
			["cg_ea1",nil,25],
			["cg_et1",nil,25],
			["cg_evolution1",nil,25],
			["cg_ferrari1",nil,25],
			["cg_gameover1",nil,25],
			["cg_gamerepeat1",nil,25],
			["cg_got1",nil,25],
			["cg_hand1",nil,25],
			["cg_hearts1",nil,25],
			["cg_homer1",nil,25],
			["cg_illuminati1",nil,25],
			["cg_jason1",nil,25],
			["cg_joker1",nil,25],
			["cg_kfc1",nil,25],
			["cg_lambo1",nil,25],
			["cg_lego1",nil,25],
			["cg_loading1",nil,25],
			["cg_mario1",nil,25],
			["cg_mayan1",nil,25],
			["cg_mtv1",nil,25],
			["cg_nike1",nil,25],
			["cg_masterrace1",nil,25],
			["cg_peanut1",nil,25],
			["cg_pepsi1",nil,25],
			["cg_pika1",nil,25],
			["cg_steam1",nil,25],
			["cg_stoned1",nil,25],
			["cg_strippers1",nil,25],
			["cg_superman1",nil,25],
			["cg_taylorswift1",nil,25],
			["cg_turtles1",nil,25],
			["cg_upyours1",nil,25],
			["cg_wow1",nil,25],
			["cg_jounie1",nil,25]
		];
	};

	//Hats
	case 1:
	{
		[

			["TRYK_Kio_Balaclava",nil,10],

			["TRYK_R_CAP_BLK ","Backcappy Schwarz",10],
			["TRYK_H_Bandana_wig","Perücken Bandana",10],

			["TRYK_ESS_CAP",nil,10],
			["TRYK_ESS_CAP_tan",nil,10],
			["TRYK_H_headsetcap_Glasses",nil,10],
			["TRYK_H_headsetcap_blk_Glasses",nil,10],
			["TRYK_r_cap_blk_Glasses",nil,10],
			["TRYK_R_CAP_TAN",nil,10],
			["TRYK_r_cap_tan_Glasses",nil,10],
			["TRYK_H_TACEARMUFF_H",nil,10],

			["TRYK_H_woolhat",nil,10],
			["TRYK_H_woolhat_WH",nil,10],
			["TRYK_H_woolhat_cu",nil,10],
			["TRYK_H_woolhat_CW",nil,10],

			["H_Watchcap_cbr",nil,10],
			["H_Watchcap_camo",nil,10],
			["H_Watchcap_blk",nil,10],
			["H_Watchcap_khk",nil,10],

			["H_Booniehat_DMARPAT",nil,10],
			["H_Booniehat_rgr",nil,10],
			["H_Booniehat_GCAMO",nil,10],

			["H_Hat_Pagri",nil,10],
			["H_Hat_Pagri_B",nil,10],
			["H_Hat_Pagri_C",nil,10],

			["H_Hat_HelmetCrewR",nil,10],
			["H_Hat_Pakol",nil,10],

			["H_Hat_Beret_Basque_A",nil,10],
			["H_Hat_Beret_Basque_B",nil,10],
			["H_Hat_Beret_Basque_C",nil,10],
			["H_Hat_Beret_Basque_D",nil,10],

			["H_Hat_HelmetT","Kriegshelm",10],
			["H_Hat_HelmetA","Kriegshelm Grün",10],
			["H_Hat_HelmetC","Kriegshelm Tarnfleck",10],
			["H_Hat_HelmetConical","Asia Hut",10],
			["H_Hat_Boonie_Cowboy","Cowboy Hut",10],
			["H_Hat_CapSov_A","Sovjet Braun",10],
			["H_Hat_CapSov_B","Sovjet Schwarz",10],
			["H_Hat_CapSov_C","Sovjet Grün",10],

			["TRYK_H_Booniehat_JSDF","Army Hut",10],
			["TRYK_H_wig","Perücke",10],
			["TRYK_H_Bandana_H",nil,10],
			["TRYK_H_Bandana_wig_g",nil,10],

			["H_Hat_Ushanka",nil,10],
			["H_Hat_Ushanka_Rnd_A",nil,10],
			["H_Hat_Ushanka_Rnd_B",nil,10],
			["H_Hat_Ushanka_Rnd_C",nil,10],
			["H_Hat_Ushanka_Rnd_D",nil,10],

			["H_Hat_Turban_A",nil,10],
			["H_Hat_Turban_B",nil,10],
			["H_Hat_Turban_C",nil,10],
			["H_Hat_Turban_D",nil,10],
			["H_Hat_Turban_E",nil,10],

			["H_Hat_Taqiyah_A",nil,10],
			["H_Hat_Taqiyah_B",nil,10],
			["H_Hat_Taqiyah_C",nil,10],
			["H_Hat_Taqiyah_D",nil,10],
			["H_Hat_Taqiyah_E",nil,10],

			["H_Bandanna_blu",nil,10],
			["H_Bandanna_gry",nil,10],
			["H_Bandanna_surfer_grn",nil,10],
			["H_Bandanna_surfer_blk",nil,10],
			["H_Bandanna_camo",nil,10],
			["H_Hat_Boonie_Flecktarn",nil,10],
			["H_Hat_Boonie_Green",nil,10],
			["H_Hat_Boonie_Marpat",nil,10],
			["H_Hat_Boonie_Tiger",nil,10],
			["H_Hat_Boonie_Woodland",nil,10],
			["H_Booniehat_khk_hs",nil,10],
			["H_Booniehat_mcamo",nil,10],
			["H_Booniehat_oli",nil,10],
			["H_Booniehat_dgtl",nil,10],
			["H_Hat_Boonie_Cowboy",nil,10],
			["ALE_H_Cowboy_Black",nil,10],
			["ALE_H_Cowboy_White",nil,10],
			["H_Hat_Golf",nil,10],
			["H_Hat_Golf_Black",nil,10],
			["H_Hat_Golf_Blue",nil,10],

			["TRYK_H_headset2",nil,10],
			["H_ALFR_Headset",nil,10],
			["H_Hat_camo",nil,10],
			["A3L_longhairblack",nil,10],
			["A3L_longhairblond",nil,10],
			["A3L_longhairbrown",nil,10],
			["H_Cap_surfer",nil,10],
			["H_MilCap_blue",nil,10],
			["H_MilCap_gry",nil,10],
			["H_MilCap_dgtl",nil,10],
			["H_MilCap_mcamo",nil,10],
			["H_MilCap_ocamo",nil,10],
			["ALE_H_NewEra_Black",nil,10],
			["ALE_H_NewEra_Cyan",nil,10],
			["ALE_H_NewEra_Superman",nil,10],
			["ALE_H_NewEra_Monster",nil,10],
			["ALE_H_NewEra_Lakers",nil,10],
			["ALE_H_NewEra_Redsox",nil,10],
			["ALE_H_Cowboy_Brown",nil,10],
			["ALE_H_Cowboy_Black",nil,10],
			["ALE_H_Cowboy_White",nil,10],
			["ALE_H_NewEra_Rouge",nil,10],

			["H_ALFR_Dallas_Mask",nil,25],
			["H_ALFR_Samurai_Mask",nil,25],
			["H_ALFR_Sheep_Mask",nil,25],
			["H_ALFR_Headset",nil,25],
			["H_ALFR_HorseMask",nil,25],
			["H_ALFR_DinoMask",nil,25],
			["cg_dinomask",nil,25],
			["cg_dinomask_p",nil,25],
			["cg_dinomask_r",nil,25],
			["H_ALFR_HorseMask_pnk",nil,25],
			["cg_horsehead",nil,25],
			["cg_horsehead_2",nil,25],
			["cg_horsehead_blk",nil,25],
			["cg_horsehead_pnk",nil,25],

			["H_ALFR_Heist_Mask_1",nil,25],
			["H_ALFR_Heist_Mask_2",nil,25],
			["H_ALFR_Heist_Mask_3",nil,25],
			["H_ALFR_Heist_Mask_4",nil,25],
			["H_ALFR_Heist_Mask_5",nil,25],
			["H_ALFR_Heist_Mask_6",nil,25],
			["H_ALFR_Heist_Mask_7",nil,25],

			["Kio_Hat",nil,25],
			["Kio_Capital_Hat",nil,25],
			["Kio_Spinning_Hat",nil,25],
			["Kio_Santa_Hat",nil,25],
			["kio_no1_hat",nil,25],
			["kio_pirate_hat",nil,25],
			["Kio_Afro_Hat",nil,25],
			["kio_vfv_mask",nil,25],

			["H_ALFR_OVERKILL_I",nil,25],
			["H_ALFR_OVERKILL_II",nil,25],
			["H_ALFR_OVERKILL_III",nil,25],
			["H_ALFR_OVERKILL_IV",nil,25],

			["Masque_Santa","Scarry Santa",25],
			["Masque_archNemesis","Monster Maske",25],
			["Masque_Smiley","Scarry Clown",25],
			["Masque_Religieuse","Nonnen Maske",25],
			["Masque_Macrilleuse","Scarry Clown (Klein)",25],
			["Masque_Unic","Einhorn Maske",25],

			["Gorb_Gingerbread1",nil,50],
			["Gorb_AngryGingerbread3",nil,50],
			["Gorb_PuddingHat",nil,50],
			["Gorb_PuddingMask1",nil,50],
			["Gorb_PuddingMask2",nil,50],
			["Gorb_CoolElfMask1",nil,50],
			["Gorb_CoolElfMask2",nil,50],
			["Gorb_CoolElfMask3",nil,50],
			["Gorb_Elf",nil,50],
			["Gorb_ElfMask1",nil,50],
			["Gorb_ElfMask2",nil,50],
			["Gorb_ElfMask3",nil,50],
			["Gorb_FestiveHat1",nil,50],
			["Gorb_FestiveHat2",nil,50],
			["Gorb_FestiveHat3",nil,50],
			["Gorb_FestiveHat4",nil,50],
			["Gorb_FestiveHat5",nil,50],
			["Gorb_FestiveHat6",nil,50],
			["Gorb_FestiveHat7",nil,50],
			["Gorb_FestiveHat8",nil,50],
			["Gorb_PlaidHat1",nil,50],
			["Gorb_PlaidHat2",nil,50],
			["Gorb_PlaidHat3",nil,50],
			["Gorb_PlaidHat4",nil,50],
			["Gorb_KnittedHat1",nil,50],
			["Gorb_KnittedHat2",nil,50],
			["Gorb_KnittedHat3",nil,50],
			["Gorb_KnittedHat4",nil,50],
			["Gorb_MrsClaus1",nil,50],
			["Gorb_MrsClaus2",nil,50],
			["Gorb_MrsClaus3",nil,50],
			["Gorb_Penguin",nil,50],
			["Gorb_Reindeer",nil,50],
			["Gorb_RoughSantaClaus1",nil,50],
			["Gorb_RoughSantaClaus2",nil,50],
			["Gorb_RoughSantaClaus3",nil,50],
			["Gorb_SantaHat",nil,50],
			["Gorb_SantaHat_Green",nil,50],
			["Gorb_Santa_White",nil,50],
			["Gorb_Santa_Tan",nil,50],
			["Gorb_Santa_Black",nil,50],
			["Gorb_Snowman",nil,50],
			["Gorb_TreeMask1",nil,50],
			["Gorb_TreeMask2",nil,50],
			["Gorb_TreeMask3",nil,50],
			["Gorb_TreeMask4",nil,50],
			["Gorb_TreeMask5",nil,50],
			["Gorb_TreeMask6",nil,50],
			["Gorb_TurkeyMask1",nil,50],
			["Gorb_TurkeyMask2",nil,50],
			["Gorb_TurkeyMask3",nil,50],
			["Gorb_UglyMrsClaus1",nil,50],
			["Gorb_UglyMrsClaus2",nil,50],
			["Gorb_UglyMrsClaus3",nil,50],

			["Masque_Alien1",nil,50],
			["Masque_Anonymous",nil,50],
			["Masque_archNemesis",nil,50],
			["Masque_Arnold",nil,50],
			["Masque_Aubrey",nil,50],
			["Masque_Bonnie",nil,50],
			["Masque_Bush",nil,50],
			["Masque_Chains",nil,50],
			["Masque_Chuck",nil,50],
			["Masque_Clinton",nil,50],
			["Masque_Clover",nil,50],
			["Masque_Dallas",nil,50],
			["Masque_Fish",nil,50],
			["Masque_forceAlpha",nil,50],
			["Masque_Gombo",nil,50],
			["Masque_GdG",nil,50],
			["Masque_Hockey",nil,50],
			["Masque_Hoxton",nil,50],
			["Masque_Incendiaire",nil,50],
			["Masque_Lincoln",nil,50],
			["Masque_Lion",nil,50],
			["Masque_Macrilleuse",nil,50],
			["Masque_Mark",nil,50],
			["Masque_Metalhead",nil,50],
			["Masque_Momie",nil,50],
			["Masque_Optimiste",nil,50],
			["Masque_Orc",nil,50],
			["Masque_Religieuse",nil,50],
			["Masque_Santa",nil,50],
			["Masque_Smiley",nil,50],
			["Masque_Mempo",nil,50],
			["Masque_speedRunner",nil,50],
			["Masque_Unic",nil,50],
			["Masque_Wolfv2",nil,50],
			["Masque_zeus",nil,50],

			["H_GingerbreadMask",nil,50],
			["H_UltronMask",nil,50],
			["H_KermitMask",nil,50],
			["H_JasonMask",nil,50],
			["H_RAAMMask",nil,50],
			["H_HulkMask",nil,50],
			["H_GrantMask",nil,50],
			["H_AntmanMask",nil,50],
			["H_AugustusMask",nil,50],
			["H_GuyFawkesMask",nil,50],
			["H_BatmanMask",nil,50],
			["H_BobaMask",nil,50], //#Justin BIEBER KaneHill
			["H_DeadpoolMask",nil,50],
			["H_FranklinMask",nil,50],
			["H_LincolnMask",nil,50],
			["H_MickeyMask",nil,50],
			["H_NixonMask",nil,50],
			["H_ObamaMask",nil,50],
			["H_PatriotMask",nil,50],
			["H_ShrekMask",nil,50],
			["H_ScarecrowMask",nil,50],
			["H_SpidermanMask",nil,50],
			["H_SpongebobMask",nil,50],
			["H_SquidwardMask",nil,50],
			["H_StarFoxMask",nil,50],
			["H_WashingtonMask",nil,50],
			["H_VenomMask",nil,50],

			["A3L_Legoman","Legokopf",50],
			["A3L_Halloween_Pumpkinhead","Pumpkin",50],
			["A3L_Halloween_PredatorMask","Predator",50],
			["A3L_Halloween_JigSaw","Jigsaw",50],
			["A3L_soa_helmet","Biker Helm",50],
			["A3L_gangster_hat","Gangster Maske",50],
			["A3L_Mask","Maske",50],
			["A3L_Crown","Krone",50],
			["A3L_Sombrero","Sombrero",50],
			["A3L_SkateHelmet_green",nil,50],
			["A3L_mexicanhat","Mexican Hut",50],
			["A3L_russianhat",nil,50],
			["jokermask",nil,50],
			["cowboyhat",nil,50]
		];
	};

	//Glasses
	case 2:
	{
		[
			["G_Aviator",nil,5],
			["G_Lady_Blue",nil,5],
			["G_Spectacles_Tinted",nil,5],
			["G_Squares",nil,5],
			["G_Sport_Red",nil,5],
			["G_Sport_Blackyellow",nil,5],
			["G_Sport_BlackWhite",nil,5],
			["G_Sport_Checkered",nil,5],
			["G_Sport_Blackred",nil,5],
			["G_Sport_Greenblack",nil,5],
			["G_Tactical_Clear",nil,5],
			["G_Tactical_Black",nil,5],
			["G_Lady_Mirror",nil,5],
			["G_Lady_Dark",nil,5],
			["G_Lady_Blue",nil,5],

			["L_Shemagh_Gry",nil,5],
			["L_Shemagh_OD",nil,5],
			["L_Shemagh_Red",nil,5],
			["L_shemagh_white",nil,5],

			["NeckTight_Dmaripat",nil,5],
			["NeckTight_Gry",nil,5],
			["NeckTight_OD",nil,5],
			["NeckTight_Red",nil,5],
			["NeckTight_Tan",nil,5],
			["NeckTight",nil,5],

			["H_ALFR_SkiMask_Glasses_6",nil,5],
			["H_ALFR_SkiMask_Glasses_5",nil,5],
			["H_ALFR_SkiMask_Glasses_4",nil,5],
			["H_ALFR_SkiMask_Glasses_7",nil,5],
			["H_ALFR_SkiMask_Glasses_8",nil,5],
			["H_ALFR_SkiMask_Glasses_3",nil,5],
			["H_ALFR_SkiMask_Glasses_1",nil,5],
			["H_ALFR_SkiMask_Glasses_2",nil,5],

			["Masque_Solitaire",nil,5],
			["Masque_Chirurgical",nil,5],
			["A3L_FatHead",nil,5],

			["SFG_Tac_smallBeardD",nil,5],
			["SFG_Tac_BeardD","Bart (Dunkel)",5],
			["SFG_Tac_ChopsD","Mutton Chops (Dunkel)",5],
			["SFG_Tac_moustacheD","Moustache (Dunkel)",5],
			["SFG_Tac_chinlessbD","Chinless Beard (Dunkel)",5],

			["SFG_Tac_smallBeardG",nil,5],
			["SFG_Tac_BeardG","Bart (Ginger)",5],
			["SFG_Tac_ChopsG","Mutton Chops (Ginger)",5],
			["SFG_Tac_moustacheG","Moustache (Ginger)",5],
			["SFG_Tac_chinlessbG","Chinless Beard (Ginger)",5],

			["SFG_Tac_smallBeardO",nil,5],
			["SFG_Tac_BeardO","Bart (Alt)",5],
			["SFG_Tac_ChopsO","Mutton Chops (Alt)",5],
			["SFG_Tac_moustacheO","Moustache (Alt)",5],
			["SFG_Tac_chinlessbO","Chinless Beard (Alt)",5],

			["SFG_Tac_smallBeardB",nil,5],
			["SFG_Tac_BeardB","Bart (Blond)",5],
			["SFG_Tac_ChopsB","Mutton Chops (Blond)",5],
			["SFG_Tac_moustacheB","Moustache (Blond)",5],
			["SFG_Tac_chinlessbB","Chinless Beard (Blond)",5],

			["TRYK_Beard_BW","Vollbart",5],
			["TRYK_Beard_BW2",nil,5],
			["TRYK_Beard_BW3",nil,5],
			["TRYK_Beard_BW4",nil,5],

			["TRYK_Beard","Vollbart",5],
			["TRYK_Beard2",nil,5],
			["TRYK_Beard3","Vollbart",5],
			["TRYK_Beard4",nil,5],

			["TRYK_Beard_Gr",nil,5],
			["TRYK_Beard_Gr2",nil,5],
			["TRYK_Beard_Gr3","Vollbart",5],
			["TRYK_Beard_Gr4",nil,5],

			["TRYK_Beard_BK",nil,5],
			["TRYK_Beard_BK2","Vollbart",5],
			["TRYK_Beard_BK3","Vollbart",5],
			["TRYK_Beard_BK4","Vollbart",5],

			["TRYK_headset_Glasses",nil,5]
		];
	};

	//Vest
	case 3:
	{
		[
			["V_BandollierB_cbr",nil,100],
			["V_BandollierB_khk",nil,100],
			["V_BandollierB_oli",nil,100],
			["V_BandollierB_blk",nil,100],
			["V_Rangemaster_belt",nil,100],
			["A3L_SpiderVest",nil,100],
			["A3L_SpookyVest",nil,100]
		];
	};

	//Backpacks
	case 4:
	{
		[
			["domepokemon",nil,75],
			["domepony",nil,75],
			["domegraffiti",nil,75],
			["domebuhse",nil,75],
			["domekappa_s",nil,75],
			["domekappa_blau",nil,75],
			["domekappa_p",nil,75],
			["domekappa_t",nil,75],
			["domekappa_w",nil,75],
			["domeadi_s",nil,75],
			["domeadi_blau",nil,75],
			["domeadi_p",nil,75],
			["domeadi_t",nil,75],
			["domeadi_w",nil,75],
			["domenik_s",nil,75],
			["domenik_blau",nil,75],
			["domenik_p",nil,75],
			["domenik_t",nil,75],
			["domenik_w",nil,75],
			["domepu_s",nil,75],
			["domepu_blau",nil,75],
			["domepu_p",nil,75],
			["domepu_t",nil,75],
			["domepu_w",nil,75],
			["TRYK_B_Carryall_wood",nil,100],
			["TRYK_B_Carryall_wh",nil,100],
			["TRYK_B_Carryall_blk",nil,100],
			["TRYK_B_Carryall_JSDF",nil,100],
			["TRYK_B_Alicepack",nil,100],
			["B_Carryall_oucamo",nil,100],
			["B_Carryall_cbr",nil,100],
			["B_Carryall_ocamo",nil,100],
			["B_Carryall_mcamo",nil,100],
			["B_Carryall_oli",nil,100],
			["B_Carryall_khk",nil,100],
			["B_Parachute",nil,500]
		];
	};
};
